'Базовые цвета

!$CLR_RED="#d60f0f"       /' Красный '/
!$CLR_BLUE="#1053b0"      /' Синий '/
!$CLR_GREEN="#37750b"     /' Зелёный '/
!$CLR_ORANGE="#fe6300"    /' Оранжевый '/
!$CLR_YELLOW="#fffb16"    /' Жёлтый '/
!$CLR_PURPLE="#7a0f91"    /' Фиолетовый '/
!$CLR_BROWN="#4b1414"     /' Коричневый '/
!$CLR_GRAY="#acacac"      /' Серый '/
!$CLR_BLACK="#000000"     /' Чёрный '/
!$CLR_WHITE="#FFFFFF"     /' Белый '/
!$CLR_LIGHTBLUE="#67a7ff" /' Голубой '/
!$CLR_PINK="#fe59db"      /' Розовый '/

'Оттенки цветов
'Наименование переменной строится как <БАЗОВЫЙ ЦВЕТ>_<НАСЫЩЕННОСТЬ> (от 100 до 900)
'Базовые цвета приняты с насыщенностью 500
!$CLR_RED_100='#f7cfcf'
!$CLR_RED_200='#ef9f9f'
!$CLR_RED_300='#e66f6f'
!$CLR_RED_400='#de3f3f'
!$CLR_RED_500='#d60f0f'
!$CLR_RED_600='#ab0c0c'
!$CLR_RED_700='#800909'
!$CLR_RED_800='#560606'
!$CLR_RED_900='#2b0303'

!$CLR_BLUE_100='#cfddef'
!$CLR_BLUE_200='#9fbadf'
!$CLR_BLUE_300='#7098d0'
!$CLR_BLUE_400='#4075c0'
!$CLR_BLUE_500='#1053b0'
!$CLR_BLUE_600='#0d428d'
!$CLR_BLUE_700='#0a326a'
!$CLR_BLUE_800='#062146'
!$CLR_BLUE_900='#031123'

!$CLR_GREEN_100='#d7e3ce'
!$CLR_GREEN_200='#afc89d'
!$CLR_GREEN_300='#87ac6d'
!$CLR_GREEN_400='#5f913c'
!$CLR_GREEN_500='#37750b'
!$CLR_GREEN_600='#2c5e09'
!$CLR_GREEN_700='#214607'
!$CLR_GREEN_800='#162f04'
!$CLR_GREEN_900='#0b1702'

!$CLR_ORANGE_100='#ffe0cc'
!$CLR_ORANGE_200='#ffc199'
!$CLR_ORANGE_300='#fea166'
!$CLR_ORANGE_400='#fe8233'
!$CLR_ORANGE_500='#fe6300'
!$CLR_ORANGE_600='#cb4f00'
!$CLR_ORANGE_700='#983b00'
!$CLR_ORANGE_800='#662800'
!$CLR_ORANGE_900='#331400'

!$CLR_YELLOW_100='#fffed0'
!$CLR_YELLOW_200='#fffda2'
!$CLR_YELLOW_300='#fffd73'
!$CLR_YELLOW_400='#fffc45'
!$CLR_YELLOW_500='#fffb16'
!$CLR_YELLOW_600='#ccc912'
!$CLR_YELLOW_700='#99970d'
!$CLR_YELLOW_800='#666409'
!$CLR_YELLOW_900='#333204'

!$CLR_PURPLE_100='#e4cfe9'
!$CLR_PURPLE_200='#ca9fd3'
!$CLR_PURPLE_300='#af6fbd'
!$CLR_PURPLE_400='#953fa7'
!$CLR_PURPLE_500='#7a0f91'
!$CLR_PURPLE_600='#620c74'
!$CLR_PURPLE_700='#490957'
!$CLR_PURPLE_800='#31063a'
!$CLR_PURPLE_900='#18031d'

!$CLR_BROWN_100='#dbd0d0'
!$CLR_BROWN_200='#b7a1a1'
!$CLR_BROWN_300='#937272'
!$CLR_BROWN_400='#6f4343'
!$CLR_BROWN_500='#4b1414'
!$CLR_BROWN_600='#3c1010'
!$CLR_BROWN_700='#2d0c0c'
!$CLR_BROWN_800='#1e0808'
!$CLR_BROWN_900='#0f0404'

!$CLR_GRAY_100='#eeeeee'
!$CLR_GRAY_200='#dedede'
!$CLR_GRAY_300='#cdcdcd'
!$CLR_GRAY_400='#bdbdbd'
!$CLR_GRAY_500='#acacac'
!$CLR_GRAY_600='#8a8a8a'
!$CLR_GRAY_700='#676767'
!$CLR_GRAY_800='#454545'
!$CLR_GRAY_900='#222222'

!$CLR_LIGHTBLUE_100='#e1edff'
!$CLR_LIGHTBLUE_200='#c2dcff'
!$CLR_LIGHTBLUE_300='#a4caff'
!$CLR_LIGHTBLUE_400='#85b9ff'
!$CLR_LIGHTBLUE_500='#67a7ff'
!$CLR_LIGHTBLUE_600='#5286cc'
!$CLR_LIGHTBLUE_700='#3e6499'
!$CLR_LIGHTBLUE_800='#294366'
!$CLR_LIGHTBLUE_900='#152133'

!$CLR_PINK_100='#ffdef8'
!$CLR_PINK_200='#ffbdf1'
!$CLR_PINK_300='#fe9be9'
!$CLR_PINK_400='#fe7ae2'
!$CLR_PINK_500='#fe59db'
!$CLR_PINK_600='#cb47af'
!$CLR_PINK_700='#983583'
!$CLR_PINK_800='#662458'
!$CLR_PINK_900='#33122c'

'Специальные цвета
!$CLR_SUCCESS=$CLR_GREEN_100     /' Успешно '/
!$CLR_ERROR=$CLR_RED_100         /' Ошибка '/
!$CLR_ALT=$CLR_BLUE_100          /' Альтернатива '/
!$CLR_EXCEPTION=$CLR_PURPLE_200  /' Исключение '/

!$GRD_CLR_RED=$CLR_RED_300 / $CLR_RED_100
!$GRD_CLR_BLUE=$CLR_BLUE_300 / $CLR_BLUE_100
!$GRD_CLR_GREEN=$CLR_GREEN_300 / $CLR_GREEN_100
!$GRD_CLR_ORANGE=$CLR_ORANGE_300 / $CLR_ORANGE_100
!$GRD_CLR_YELLOW=$CLR_YELLOW_300 / $CLR_YELLOW_100
!$GRD_CLR_PURPLE=$CLR_PURPLE_300 / $CLR_PURPLE_100
!$GRD_CLR_BROWN=$CLR_BROWN_300 / $CLR_BROWN_100
!$GRD_CLR_GRAY=$CLR_GRAY_300 / $CLR_GRAY_100
!$GRD_CLR_LIGHTBLUE=$CLR_LIGHTBLUE_300 / $CLR_LIGHTBLUE_100
!$GRD_CLR_PINK=$CLR_PINK_300 / $CLR_PINK_100

!$CLR_TELE2_1='#1f2229'
!$CLR_TELE2_2='#ff59a3'
!$CLR_TELE2_3='#00b4ee'
!$CLR_TELE2_4='#c882ff'

!$CLR_MEGAFON_1='#00b956'
!$CLR_MEGAFON_2='#731982'

!$CLR_MTS_1='#cc061a'

!$CLR_BEELINE_1='#ffcc00'
!$CLR_BEELINE_2='#13171b'

!$CLR_YOTA_1='#00aeef'

!$CLR_MOTIV_1='#fa6600'

!$CLR_ROSTELECOM_1='#7700ff'
!$CLR_ROSTELECOM_2='#ff4f12'

!$CLR_DEVINO_1='#717fff'

!$CLR_SMSTRAFFIC_1='#004b93'

!$CLR_EDNA_1='#00ea43'

!$CLR_A1S_1='#dc220b'
!$CLR_A1S_2='#2c2f30'

!$CLR_VIBER_1='#7360f2'

!$CLR_WHATSAPP_1='#075E54'
!$CLR_WHATSAPP_2='#25D366'

!$CLR_TELEGRAM_1='#24A1DE'

!$CLR_SKYPE_1='#00AFF0'

!$CLR_ZOOM_1='#0B5CFF'

skinparam maxwidth 1024

skinparam objectBackGroundColor $GRD_CLR_BLUE
skinparam classBackGroundColor $GRD_CLR_GREEN
skinparam enumBackGroundColor $GRD_CLR_PINK
skinparam packageBackGroundColor $GRD_CLR_GRAY
skinparam ObjectBorderColor $CLR_BLUE_700
skinparam ObjectBorderThickness 1
skinparam ObjectBorderRadius 3
skinparam ClassBorderColor $CLR_GREEN_900

skinparam ParticipantFontColor $CLR_BLACK
skinparam ParticipantBackgroundColor $GRD_CLR_BLUE
skinparam ParticipantBorderColor $CLR_BLACK
skinparam ActorBorderColor $CLR_BLACK
skinparam ActorBackgroundColor $GRD_CLR_BLUE
skinparam DatabaseBackgroundColor $GRD_CLR_BLUE
skinparam CollectionsBackgroundColor $GRD_CLR_BLUE
skinparam QueueBackgroundColor $GRD_CLR_BLUE

sprite $skype_s [128x128/16z] {
nTa1cgEg4ePX2W2X2kF-TtixJyxy6Lgb07Nkju4t50HZjsb6riSbfPpI4eCZClymyYd_5R-JIFz83xznbEpZk8rdkBpBuV-ZowTIYeJ7T0h7El1Fuftp_-MS
fRjuTwXNDkTzp2dSyIbseuSEkv5aV-ap4BTqQU68b-cFOBcXS-vleQjRFwcZvEPvw3oXe-IdULs__nFGZeS-ty1LpSUBbtmfxdrUBO3lMJnYryCxhiFYhySB
gJoLvtXciPeVdvazzjJtJnytpXqwYar_sJtcrdAFZXPj-JKlT-aeaRPyyEkjFA8JddPykLD7Git3Z-7VpgDZF-lylAuVGhgNvrRnTFpWLtv0Hs7lIytB69ZU
GTTpk_7Bt3SlHLU_BCO4lnNj_7TO_gL76WLMowRELJnFueWIAtbJ5KI6fX_9jBEANwY-VCUcRuqQfP4ToF0xfXzDJrO6lWCZrtumVItSJCnV3KpVcyxim2tK
l_nexlAvcd_dyjdSvOl4oiVoHqy-sKzawdnR5s63SkVLatQut_XFM_tElocyIFYUrSdbn_CVU47Hgm7uyjCwlFpC-t9Gldto3SkX3x-E7Vx8n-KbDNN4ltmP
kdei3mOTORVMDwzUlQxomxIES9a9nj-Awl5FysZx7i1LF_rynPUZ2k40T8oVxVpyvJZiQ1xtxRoE5cn0n_QpDrLnMjyV02FQzX-yEIopEbej5jCUFx_RNVzn
LjyV0DfOupcRtzayfwFlbeQ6tdXpSZB3e-z8YJKT0wYpwxYEDeEanJV_XcNZfl6wRxcX8siE8oUYwDeNmBLq9EOi5wLVHyNX1chgA9dJA43lpv_v8ty_GH7w
LPzFIxRz2UxmkPKuquZuiizQMtC4xZNZXnuU9Rff107hXzxNGkQyPNR-ZAxD84xvF5ZovgmqxFDCEPYJja7VyLmbsaFVIK_bgYy_7Tz8qjFggh-1ZePbsBrl
fQFjUuRN6HunAIT0zVEqZfDK5uRk7nCdTRIOEXArKihtmCxgQ1dqoxiuuRT_pIFMz7UCZxlEwYZNVjRqTzzp8xUzpkb-GP9mNgTr-5RpeIFXaHVgdcypObql
VvqQUWtf-lovnSDdRC2Ywzd_54lhCa7Krk6h6m2T0tuio44lKdpejK_w8sXtnVeakwofMdIzzariwfBg1toMgaocRclhuDbXOYqUsul8yH_ZjVynQ7L-_VZ1
_2arT8o_YZwPVPkw-FK_Vp6D4rWTxu5SGyVoY_nwfqq7Eee3F6qw__Qb_hEAg_MwFE3dIbTzb7Rwr0Oaw0elKljEQhtEZV7GTHyjjLvNkYRW2dITby_vGxIs
Vs8uJQUuTl5VlpxNNdl81jlGxR91rvPVFZpxqT_j-5TV7Tcq5UZTosSxyU8YcqH7trpaZztFmoTJv-LQHUNV5JdppNAZhljYTkMdTF2Olt3O-_IS3Xu-DQwG
v_XtZQUAlrq73x_vLFNtwk1VhveNCiVvHtduYpahtAo3__Zw8pNSgOFNbuyStwE3tqs_EDFAJkZwwlN3ZoW_mh_32tExKExImNzzP_JiTb47N_i5XqyhhDSN
_-7h0M3wMZQLwulV--3rF5_GmLU-E3DIuCjwpNipME0flLuyScOyjnMPrMj-isOgYbil3ls89pET3TlMYKEl-JMQQraNrktL7Zlm_UATkIFhVKoo8Kalh1iw
-kgHpCqHuLa1-qHV5skUBFAwho3epsLpET4vFexZDVXLy-ksUJB_C28NC__0HVBYBRNn_m4
}

sprite $telegram_s [128x128/16z] {
lTi9ckGi20PWFb0Je-BzJ_kliy-a969y3z2KY1jvcgQ0HS9Pc_wZrHn46BG79EQcVz1o5BmTEnNzg2R1Qy5FDSa2MeuFVU1aMWcXw4CbW1P1R3eZOddq_RyW
D7LeWLpuKgTBQ1gIBf10SwJe4bLeHbG7TmgGTQ4CUeQhBjM4dWYwNF1DlLyagwIlIBxmViaNtY_vmlibN-dvHSV2sx0CMLydT0zLNzUORcNT8CDKU_iNWQY3
lmHGT9CAryRZbznBR_qCNBfHWMlZMxyDekbM3Owblxu4eTl1DNo_v9jzFxnP_3a8XsAzYXHTwXGOtb0LhsnzLm1z9RPDyD1LMcJxdduw5f-jyGPJ1OekaPX-
nQPDEA-TTNlyl2hz1y_TgE18lwNJA9PhG7BMdECnTNWtdyJqoQcVDIB2-iJRxrIOd_xCD6Iv1qP7uWTWEOIpA_7ErsmcQgigFbpo_455M9Hupghy_4uDNfFu
-AVMmgb3BDx4VslJXvadZOY_uX5l6Yiw9i5uhm3T3_ucF7Jio3fs2UZpu3LClcXBDHskWy5hcEvdD4FYHuFNy58dimHOlax9H3VB_n4LST3HQ-fnyUZJtA2V
1_KuOEiJLwORh9xwWsdmMfZkY5hKcVZnsoJ1syhEp_lKd4sVrKurAD6mxToDwmHzKDNW4Brr1RuPlAL4eHP11kbXt4rgeWMV4eHre1q2-X-asCBRov-X1kKC
8d8qDOQtbp-elVGXwrGBejmdNA2HsWqkejWd28sWMoGYwHEOHjWw3hmJNyn_f_RdCet4Rj3e7wbFIA3FSZSuRp9bCBgUgBcCqQTey9S_Rb9bazbP_jUWL1qf
a6uG1hbofE2mfv_ex7rr2gudYvYxmudPyXFwgdG73NFbrq1VXUvoOARy8dq3xNrf2b8Vms2tzbH1CHszXWIOgJoSVWoEAy-Hb4p3joN0hefz-0hwMUWBP0OH
SJKMlxbax3JdguyLs4uCE__zDVLj3le3rBv9W-7CtfNz_JEGw0Poz_2_tT3wwvJfdkoP_7kXlonutar-YKRIjl3xVy115cbB-Fq_895Lt11-zp8Cz8IqlfGA
FSEvBtGnFONKbqaWi_Lpq8JirgVW04sJqfsAa0U2TWUD82SaNztv8QahkXz2xG-r25e8SlO7ie1MGxYwoHL0xu0SRP3sSyF_W5_wvt4dOTe3B79KxV_HUWHX
q9I_0G
}

sprite $zoom_s [128x128/16z] {
xC413G000C8W-wUsnmUi20000000uAoM1wxW80n4QIwf__wtNP5HOen_ZNPKOR2V2It4GLJDpazd2Q6PRg_DLl51ZT0kaRz-11rBU-XoTvxAUQBBVfihaxEQ
el_Ggv_N4-qb5i1mlBGYZw9foI1u-sXkD5esgPrRayCII_vD0GS5F98POvayAo2xJtgkgvzQA80YVsi1WG8eC8ANELXEWP_Q8pumHlA3tmcMZBFC6yR1QugP
mYkt1GEItgBJ5n1LmL_xyYEMQuPLa8o7DQFsUAZr-chOQ0H3WTU27OkKN-C_38ylFExvjbvGCAQ9LFLUSsih7My5vE_nM-sDnUf-3kDTFOEHmovku1kYo5YD
DoCUmjbJ5sZ9zfRIqJtApbE4pWZw5J_YiViAh3dP-Od7y5xn8pvnPno_voD0obi-y9PLiVj-pyVkhA_u4P_ah_pQ-TixViGdsj-iFvSt_8Z_VFzb7ldj_-o_
Y8Sqdh6szPkjfXI7lpz_4GyjeQ_8VV-qSFza_NWr_uZthoZLxF3k_YNpQ8NtTtv3hWrulm1MGIuLU1o9UdlbebT5kxtW7_VhNKVXZOMwGuizPCW3IQkroZtm
iVJtV50cBLS1U-XVaQbxv-oTP8YIlk1puAy1OWLi4q5Riammu--F9rGT-Qa4laQuVKjTnicBtxTR-3S5tszbsaP-AZC_YvvHpqAh7Y2erEHLH9QxChPy1q8V
DLdR6AKh-1R1dwa-hdHXtyygyEgOhOHHjVcWV-t10Gq000328FkdjiS7B0a000000803
}

sprite $viber_s [128x128/16z] {
nPlfblCc343HnchG-xzjquddu2Q8mR5xSlzrlR8iXC3vt4c0VCnbgwqrVT8UrBgLd8AW-_y02GyUyjfqH6jRIU61Pt0tGo76j3LTefKKexyj5HXosVGqMya2
xYA0GI_X0JwNW-WDCC3bHx-SXA_OEuBd8a3HcpdJ6e1rHlA4y0f9o3fbkIkGrp55TkyuwYSSrS2JMu5rHAIHrmf4Xhd8_4dkssUD17mkJL_WlvlyQyxJvvqK
99NNCdHpfEgH7EZgnf6g7gWorszwe7Xobq6VcdOAEniksgc1tIsGBsj5I54xsut317lj15oflSZk4lR_kid2mW_axkKO0BiH68qStHw0XpyUFwEx7vct8JmK
wNBouSbYGvocbytmR23hWoIu50FD7X2ByNeM_u-H4DPtjW3Ju5Q1b_qLtPJ3J8Ml_wSmppuI8OxVF_dScmOk9k1rHyNUe4SQ3jF61O1x_85XkXVq15YHiVsV
HPnEhC_DLcYM0CCFHNSA3VRGnRO4FoDWuaa2uhZ8mHuGG98kBmsCHRK8B2G0XjLVtuANCXsWG1umz4f9qm1u6_aXgXglcAiUgJXOjpK7xyazeLXry_3d4XHO
I7ylZF7ow9chAJ3iYashcG4PlG0mnxEedM7h0cOEvHbQndsvLBk7o-W5KE-YrkDFUpSHXqDzOkW1s2i01itFk__Ycxw3umOf_HzYijkuVozbKCiVTK0mRwPw
06tFnSIVuStVPCMlE3qxuUyRfJzE6Drl3kT1Xu0xSfX0UW31YfFpm6-jVjnq1BtCjllklmSGOT_Gs0s0zm94-yrc7P477I0y8-3VB4etZ7FQqoEst-k8Ccnf
0dis4kv9fQcVtwhCkrV0VluESkm1KD8ckoV3R064dcJJxv8EuC7YIxz_d_SwGkC5-FRw5BhJ1duSFJuOTLNXsU6gxAcJwG9yzLUnHkmZBOtqkm-UvIIJ2kHY
-FlodoMW171Z_ExZyjn7OEodRFdpg5uXwP74XhxxC6XZsm_9yYTq0sXGUgOVzyJ_-Cku0ABfX_5KgGTmxkU3tx5gFkEFRWXg9ytyeHSU__w7D_Z1h_aT_UQ_
tUftECz_1z7jVhdJ3tBkR2xrNh_3jf203eHAj_eTdpkT0xXVFzpYns0CFnRN_TTlPnp8RNudTWBcB-8cFqRhZ3RdWj-y6kTl-9sli_bZ7KoBVliD17S1ogj-
--k0l-3dyeb_x-ixzK80Kaq_k3cYrmFeyszvzMTSlq9kVZI3vuX_-tkwv_Fdl0RLu_2eac3Htuie3-Pl0qggFLmuwklWPcdj_1K6ERMWJJiUXrDYGbZnWzlX
CykAgXvWXD4zdS0PF-XEMEuV7Oy8W5IqCxqenNZ9tpyJTaBGDmAPxMVz_cC-ZSn93EVlVyGj0LuN49WjlwC_dkxhKZyDm0zAX4xx7QUL06RbXyxD2s0EXeKK
mApy1lwDtJe-dVJRzz_fezcEmca_-E4GHPzzU0Q9EYE2dNvs1-3JsH9zKnjQ_Vu3-TFX6iYVM7yOkz-8Yzn9p5yy1LZ_08fNJXV8UQ0lTE83CFYF4j0ZMBaa
TMn_vQNvrda-0e7PDtvsqm_WroDWc5wZuFgl4zO1BBCsCZ_3Or1h5rW7WFkdYCaz9it3y-0-1W2iO-Vy3ODS2s1zhqZuvs3fyMPzNBX3visO7oyZQMKs1byF
IH9t5-YhTY8j7UzqypUbG69R_H4g9UsqV4CL0CTD3nHUkPpOgJdWnSodpTuLx1hiR9dXqsuOyZRTbEQle0EdrO1UH_17Fx-64-87zbXAYoMpuEyVtQ53VbER
zPP2wIy_Xk25YPX5V4Ywm9aw0fxxCUX90fvTEVDJn3aYVL33tlA3lzDk0vH7Vf3R__J9l130R55pQicN1mbuysFI1KgAFUrt-Y7gd9fZ284DznL_dzDhQo_M
LhUSWl-NhhxNt_L1Vl2_o0yyo_TrVrzvOT5plr_w-FeDF-c3ZToN_5Zw7lu5FwHT_nN_hXVuaXz2rt_13xxhl-07sVQJqnVyw43AFiDym-z9ylFWzWM2xYHo
tm3xkV4Rx9NN8hal0TA_gjxFFm
}

sprite $whatsapp_s [128x128/16z] {
xPldWgmg48Jj11YGzt_RkphkaN8H7SQRJ_qwOUIhhcxG3NR_GlqMbVGNehaWMlGNiULBcac-zATxUB5VPDkWl_w-_SFBmvzK-W9Rg-K2WKNLDW-FMzZXmhMF
YIvwMNYOliAl5oK61m_HHGgLLr8mrQSShBLZow_50Wx-CZewMBlm6NwXQziYz790z67nxIMGcIu6g1alggtqBOBsANWLVxQmw2gpxnrVZ-1z-ZbUr5mOfhXh
6djlLlmqQSr0FNkX0jpvVfoA6eApqi7ywi6R-6BnlDHTqnYy50oOmX0qujcDqmtrMkb1EvvzYjCjfQHKCT24PqlpT5ifC9KCtCSVBfUKfdSKat6hWQrwZ7vw
LsaGAXXem9E4EBN8-6Y0YTx7Mp-rQVHys8RNCqZCAfZzE3MhnwMW0wUpXzVqqoSQOJ6vD70SVPwdpvJ0W9eAqVtcCypzvmPe7O5Q-YgLwZytm0uwK4-VOTyr
Ap6E01FTIf_yz8p6V55tte73xEiuFQJ0nGxKqvT-UagZPHY33W1VkTRyeV_IPIQnf44o30HmLZvPYhdcO2fVKZ_71lLPPOe1bCiNnATVHpcd5dwomWJKok-n
UhzRqpO3SWYWEln7I9_thuqVg1e0aIYVCIQ3C_JJ00W3k2xVmuUvYH_7VH7v6G3nUVcZuKV3t1W0FecSJvyXFtGeQGjWg4mWnZz6aEjGt3Vnaq03YCxYrmYQ
1EZDMp26q-S0ZDz7qDWT9KFZ1683a0zd3_RjA7AnIRhp7V3XkSUc0X-bquSDm2C83nyNB_das_YqGopZO_o-mWUFRsiGU0eeysMuvhEFJNBb0I1MnVRNvx_J
yKC-dW0uVZ5UxNyE3MoyaN0-031-LdIDwS-D_5vm0FVnfyfe1yIJfTYeKOjy5gkTRJstdxweoJA-Pdoj7YtkWzi_AkEx4tvjR1R9Ctohyr7m_FKWdu1_tjt0
4C1Vpaz6-U6V7k2hKxdWuyczYuVv4JxVvoVimF1NysDIE8769_elSFxK-J4ntFyVdZ-3_NTjWFlvStxv_9tE-8vo0-FyvFbdDsOhAHx31GCffTldF_BfngDD
4Z0mf9yEMLEwU__R-TNxFvu2-1G-Wrx-D8ppcGBZzy7App_pcQ9dCA03uBz3L3_CPRazlGDVx_3doT7XIMYlDRz9YEjJdQ_0X-VVVZvND3H06hv1FJH7hE0W
EZn-CdwshYzm8MGGwv0MqY0TYEHda0FZzYz_uzNDDIMb3iKof9IqEuhuc6J8PjToFaas03hM-74pW2JZhY1_ofUj_QK1f33N3HZzhBMxmOy2T_-CZmC0_8AI
ArLxpH-xKlitlkxc95uP2DB0JpxV_SY71dJZVAL1x_03ygdG_dq0uFjVrmPkz4063AqhxFvY0phWbmKtWx9S13uNuz-43T0qtr1VZu0yu5qfVjW1-t9KuSD4
4LNAJrW-73v21pv10-IcWUJvn05PEZktnKFvnG1yccyw25Aom837yirfcNyx07IGJBW3aOO3NhjY-JY1HZY2zor4qzq3gqi7lC-x3-L305eDe6vXzBOf8Frm
SsOe7_Zg2FXlAtvf_gbHkrBvAAASJoxDJmc-Vw9G_ka0y7Fu51ZILw4pldJFyzF46SGvk_NZNtsEd-DbFVcl-PJIdu5d7BuZNpB-GtJ04wHV-_clf6Vm8-3r
F7ty8f3y9tpyaWYRNobVzE7uHmCyDB-o-nxYfq41m1xmrVPRpa-htgKd9qTyxTU_y4kmb39sBryAxpb8ez8DFF8X_WrkpAijbZSCfAJS5V2LzA7zabPs4CeC
azximcAw-ubNmDTsNzSlXIzi5DaD1ocv7nW1_FNXx_ZiOpB4AZrkVSUB7E1hxRyMMGXZqSJO1rzWi3cd0lZAxgy82d9XdBvTn3W6vvmM2RmK3vDVstttHMgx
JYyc1Nmz_kV5pZkJ2Xw--djQf1wBh-x-odyAjT35O_QNkw_CTZu4h_GstRteDNoz_SnYtdltal0R5XRN2nsAh_BbfoEtv6UcgrwR-6Rfwjn61to5hmJk5zp2
XdViRCtp6cxBfVW6s7NzlzXgvbPuzZhVzjxV-b-cvzF8csy5-ds-cFjcwyw6z-zi8mZ_ADiSm85-nUUEPBlUW5rw_z0ML45mxVilEjbUDovmj23hGBwqO5Vf
9-zVRkjkxCe2-VkdehzKkVQ-WRlNqoe-whDtWEczowcWxb-et_e3
}

sprite $smstraffic_l [300x50/16z] {
xPW7rgCw34RTi77V_sgd6F8HHUWSpEkFt6a9y8Dq4POODSCN-u6qmtnLnVP1KXkvVU3Lqwdjt8bbswlvrXLpeiUEmdPazN0qBwmuThZ6MDJ3yOtXneuaLDoJ
oSn9aIlkuHZkP9Kgpgg7imejJwYu9oEtFDiOGJqNiUN95VTSn9OdBEz90SwIM_z52SU6dDcaONBE0LzYxR-eKIk2pYSOfL86CJZrGTXsu3kE1v6TUWJZneSZ
1htMFbBnbuUiPMR8SlrWFohrtXjhlCT6NJgWTy7s4xpIdPAfuhvXoHRAoQchKd5yC6h3b7wG_e8XQ-tlnDqL8gVXjnCXJS-vmbq1dgHtsvNl5Fjd3rdBfiWQ
kxQH5roL4wVjI2GlnlWoOfvtHMLL2Bdh2W7AikIM5ouCMGXgVR-_SDLFdfEsxqKn6PAsu6eXhfYOOwUxwOei9QsrldDxoChIOeKTuz8UhY8z4Aw8HuF28ZIc
0nVIkGy2NmKoTKKZjlWf05Umkzrt7S_MB7r_o4ASJe4zmCHlIoMkCjqnumePLd9i6Dlkke9mHvQMhgyDMV7IyXxfOnrIskkgujb2ilbmbHHmASL9LvhS2hDz
mI9spnLgbUpnV-QGvP4us5tbtYlPqYDSiKgQSwNW2baLbSS_TrqPd99UySyQid3AzSoLsMyOOW_3rVxKLVsdkTeBQi6sEwu2Ms4pgmwXvGaLLtY6ULi4BNEb
wXOioayDLrZcow9lkS89Ada4Tpt-fgjCXWG9kUMPUcLvRtsZ1arTUNgR4roXSRLaPrt13gevlRnXLeEhjhu8S5MmRNbtLR6KYqWjJmiLbnKdqQaThXJo6M7g
mvLQEiZckgiQVX5h9pqAvUJfLWfS7RJ35RkUYEyCZUUBKjG9EZOSuDzSHLozlButZFlri7NL5S2LOE0u9lobhdJhW8JlEYD8v_05fGLNUfjNy65p1LngU26S
TxM-hvVr6E7QXAlvPp1rXa6ybAf4CEowtHNA2GK6Lq3xXbipvygHXbVZRv3lDLU5h-r6YKZLiw9775pf4tfC0xihB5DOk9WhhFFwegjQQqDDOEMZn5jzS4NY
kAJvXLQ4AbIFxK8O0WWHhaR6QSj7IQx67NKJVR2J0RrqnYrN5hU05Yo_hnGdHD4K9uIWIU9mXR5g7xJWQWd1VQImJhWAT13bc9llEFJ1SVpbsNH6afhZSbv8
KNGrTljzW8UhYamHGPYPhz1b46LxWVYdNT7NVUPEgXujDKVfeTFICpW-jBmfWgi4xMWjPiQLVykgdYLuovKcFTbWMGHozUJJcOiJoRjTtiiChZJEURWoUCwn
EC_DxMX0J0dULEPTOJ4gSSMuwzXeHIYJezKMjnbfjqqfNA5k5LnXICbsn3-oytEkFEvT-CXemM5pheH7B5uOhUJcoB6iCS0Lf4VYYfqzpRuxuyVeKTXppvNA
JDMLqMgT6ArCuuV15HOqkE9HhMhE5OOglMqjRFbTxhbIGMnbSlMOkT4AxtRLOn0vyYfbHIZOQbwsMjJgZFnXORDAbGJFSbfUmJOUj3an4E1gOsqabNkZ5J8I
iCwgIOnpMlqBiSjcuVvezMpop6ZrR9REy79pV3OJezMg7ilyQFLixCHevTIpAKBrQA4vFfacL8yLckEJ2VB_zLEQKtysNxvy-Ga
}

sprite $rapporto_l [300x77/16z] {
xPpfOhew44Td3LkLzt_RUqj8HuOO8sd_6vnFWZ-ZEGuXn0LUW4Z4dn0XmXCka5WTGXbV5oIQXpUwBf2r1C7A1Og-Wi5ncIf0S45QYU1LLFNGLLJr2Fory09-
Wwf__pZK1JpkMjy7p-cAzGXuHbUiny3pkI8z2fxD5UbXv6IkK1lWSxaIRO7Ev8gr2V-SY503uhU7VjuLwb52wBh78Gj9mXpfbB2mwBF6Wb0Xf2z3b39phuGl
btYnmXKIYou84nu-0iFmIRzkT6FioTTHY3flwMZtLYwvy1YQ1FsxPetva64HesVODHLPtni2v8Ka8r9OunGwM5Rn2OVbPZylH5UINhadG0ANxH40-Ev24sr3
msTezY7EcV8Cl6sgYyKmhn2GPYXF1nWCUTDL_tdhPZhYy4xZdAD7xohNHN6kIg68FPz3hQdrlS9XhdGbhovxKTztrSr6YALwJtA4YOWroUoSAuqwX9abt5qF
aokDOHSICCWAJfY8WozbJEtID5UwCbLCYCGMG9-eTnNcbVlzTWjsp_p1QBrPZrBUk5eiX9IoZZ1OQ78XddQoC0dKb4BvsWNMb02c1tzCq-J6ArxPYX3S3LxY
oghQLQSVyUtlWYQ6k0VXaIw-HdDbNWoT8rGPYlJp_WcnJm-rfZWcRqhuQix06g7SJhQjzrprQTHoTzpzFEknWvYrO0DlNnLoc-u9kxM2q5on5L_P5URdYlIu
MzzsDSRYUgHV2zwXjjiq173qfjI5zXhuyGYyUGKunfJOUN0oxsLNxAhAxL-QVD_LNfN6CG71GT6jkSgcCDMCXUwva9qfsDMU7_5lhaGhNA4fSLXXqI5NlMv9
hp3VmOqhXHsQ9DQ4h197C5pv4PWhXHfNvFVuUnX0ZhYw-VtZ__IXoXN1inXR24iXkscumb9hQi8gL-BBocSLG8-uwYgNPZ3rt6xV8SCGM_qAJP1XYXLjGl1v
QZ1N0bMk2Yicl8RnaAlQDJ_Qkr8m_5dkAnGWWnteadn0uL3r9LfsXQMBwHPNWsR9El2k639mobM5O7Xk7SWrrKELAzA5KfZeYAkkqXNFUrTKw20LGtRV-5me
e6jAwbnnvj1mOndp4LVXnOeV8Z5B37jNMEfWJOW1KZfBMNlP5PTSYNolAoIsnPgtNN6w0JMk4BBSdVOwLv8PsdtHwH5NcaTqSf9kbQx0kog4v8MhAQQ-tPNH
xghxc1sJKDcLBmPfTvK6CxMc_ZnNmsmCWPa80V3trTKVx6gS8-DcyGCFZbVOF5wPzZzhlBAgwkdbl9rgpeDKTdLxupm8l_ay-7H_nJKEb-PNTI4O2wxmc2lw
gVdLax8Q3b_Z-7bxA8QWUsFU3hzvtgwUD4Puk7pjx5TIojVEjY8jXQiNSKrLkiA2Arp3xQviDpvpWEKrcJG0XPg5c-3ADJzbw6fT-Hs5qo3WDxhATy-x2a-F
BYwkzL4AsRckS0AeTUN7fCBG3l2JhjYvigtiWZjMXW32MZmLIwnWjAsB4e3yu36OPlAbpoPCQLSCqHfofyHygeTQLtuFFoihDMjDhZH_fjVPkyhcSBIUruHi
81ony95GlQjoOR59nEzmDURc33BdNVbwwAoIBEHb1GkvAikaEZZW2gJu-Q0zgj5LbncHrNKRvwm7N1zxGx3GpOT22hdM1uHzKtTyvgeub6FfSsUohKPNkevC
7K84urSGHEEBL-Rqsdc91agv3zDd7QHf6vhs1PcyA89lYg3MbKQhj2qXmTtFazXqDhlgvfLH_aV7DGSyp_woc6AN9XMHuMxtRpf8jq8eOa_v6R9r3j-KntaH
iIcebGqJ4Ojjck8cLoRB8m1usxa26lPH1jT1B8JiCCmm4LIuSXNY37h8AMvqfJpEMmQoBnQvvHR9HNq7VSYlOSIsFOfGuSeFFSKVBmiU-rvVjv1NpyDi188L
aX22RjU_KTsNIdq7Yo63TAjJ40nUgFZrWp0OIB8HnUWUrSxcNmgOm70Qq1GEGwT2c0cbhINKnv33zyr2rI1zWhaxc4MOENEdQ2jUJi5LJGZ-N50R4JYDAs1j
0y_ZglttE6ToXMr7uAbS0RMeEekhzY4Bp-AgNHR2ILoroo8uYQjsMGGdSTKk2-6ihe1-yYzI-WKeWXRwj_wdYE7aS4DHdGwK-gAweDUs6C6uRBMRklurKmWy
5vYfBiwAkh1VG7p2H0ZdvZy
}

sprite $rapporto_s [128x128/16z] {
xTi5RYGn58JXUUJkuVkVTY5KahpmikDABVsY23yPD6douTUoBxb7XBkRsO4VP8-igGmtFcwW4SemekrPZS8fkcUrIri-xVM-qaKw2jFeA5RmKG_aZ-fUZMWx
qR8UBaY3voy21g-O0gjrfH7cdhe6KOjp0a_R15c4GiEZqF0eD3mApTP3eU6HDtvsg5dZHvUQQVbApTP7eLbyP9BPHwcPVHIQsHzV-i4AKEdjVBtUlxHX1GW_
VDlzjMEXxNX_2dxvn5kH_Eq2_SsloG-EFvxqsVTf-1H_XmmV4u1YiR_Nrx3ma-_JyDVxu6S_f-6lzS7F_lmRKAlzRLhxyrFmoy0xmHztTDp7-D6lS2xtHvtl
Brss9tjksdqh_TS_RzlFhmLzlRzVNrPzDFuDvc8VdJh_XgrO_cLqBeISvTz6wsOWMVvMBRz8_gbt8MWiV_IkX9ta7wld1yaVpRlHvFZdxeLuSVozUITY97zK
8w9VJTyv_gqw6StVkuzZWkDlNJ__Jdzqrx-K_e7a__UhKuZzbFcO__p7_H2lVuZ7xsBV_W5VSFrPI7BztNyJ46BVTJxn_lCTxo54Ffu_Y7rN-SpdJ-zv3vOQ
FrxzqFZswfl6FxoL2Z_XkyAt0nBuqNZ_mlIvxv_khTL7-T5-CDu_3jJRVIZhGml9nm_py548Xg-QW9Hz_O8BZxaK35-o0Y0bMz35tr_zTj-V8TTy_OL2i_We
DOkFKiEZbEmzP2dXaQM4HvOI7bbgjXvA3Oz2S_m1kOP7bfhZBoWqWqUUci6ZK0r-tWMgCuYMcgb7dWITF0TXX8F7tTAVTCqXt0nJ7B_6oCdX-BdY03eEmNj4
FXNno0dypm
}

sprite $edna_s [128x128/16z] {
xTf7mYid40JWJi0mgUz_MtlbR4IXub-zxm2gKJTfWd2ecTKd_zJDL7w6MPpNc_zo7sQocRht7AYkEyDBVkQwARpbdCktX0EQSjFBavZJXCQFDs5l28N6bMk2
KlW4i2_0MWBO5-0jlnNST9ml3_caE7KflIVBfNZwbKHLC7Odbmb0QzB9l4W0VHBQaJiyoYyzlm1nvYwdSalFNmKzjpfaI5jkfZ9WL-uMh3dFNuHhVk7ilJyv
GUcjxzNDv7Tgtkx5JS1whhYAgK9hL_nt_BCOFfZ1GBubhhckB2654ry6ctd9WVC_ujy4kSg0viYtvvodcNnGeFoMWAkQV6H8Vab0KPcWGBvZwLEqJ-VhbYS9
nqG-MFrgCg_DvYlq48EV7z1J97x-pDJlWzK67tyNkl1MD7tSrOADliC4fvFxdq8pdfzlcnvQn6H-sHClPVByT-R8PRAepkNhamEFomIq_Nsw_I6hV7Bw1VIu
Y3_yNk2SY6YJmm-uJq1O4l9VsTB-9fFv8SlgxC_kAR_cW2Bv_F9Vq_bxHd-J_Vdp6qeEw8xPT-jqlkqeVvU_UNRaN_FxUTsm_7eE6B9Gyij_ozyfqW32dLyW
lJhuvLVaDl4rzjgVs4vP1AUZYWQMVzccyiyUW2kt_0TwlOzHjrw77_mr0GMye1pK8tY7XxFdaF8Ede5s3Ez0MRYT2DuTgAwi9ff3jv8clwD5mxU1S-bdB4aT
yCN5l98-M-X06v42T8Kc7zx5IdbhtvPFiteIXe0zm_A3opQ-4xSlAgWtzDeUVtzduDJ1pqBjkrMy0HU0_m739Wz-0Nham4dvt2QGyk4hQ4FUGU272487hbZR
GWCuF0oz1R_bodnLfkYP7nM5upEOdxizXiPtHKxFS0dy8dxtsHAy0gj9sBpXbv5N3LMByh2_ElKawu8foUNuunEc9YWzaqW5vjpguo9PAlNr0Su4m1-38Okq
KwkFiuVwjJb_4e0R9SwtDd__1HJvbdF77ixVNDLK2FoXnkFyp1M72eaTYQigDDgu8t__D0WXipC19dpnCbg_VnZUBhjudxWvLTb7lM5VP_9PvF_fOV83rF-p
2k4gFqRDlVmrsvR3V_aD
}

sprite $edna_l [300x93/16z] {
xPpfcjie44MvnQx5lF_Jpj9nlj0que95bCKwlsQIb70TTf2jne68sTCJ9wAgt437BHLi7hUO0eXTKvrLtteonEsfmIBgWnlO9J6CKkf6GkeXuXxDbzJ3BGjs
JptSik3I616tgMwikWh81_ZZJ5ql2-a9_Z1JEQ8kGKXvbm6RNYQybolzI2VGR-HAV3h7-xYowIpwJLn9Eazu3rSspK3Um1LYceBv-rtfD8dmzxeQLsMq0A9Z
EW1_kIkR-h3uOG8-LP6_svNh4oMbuMjSuOCJhgvMjUXAO1pSG8lstq8UtWbK1sBy_lm0Nik8AsWVdcLP6IegUYqdL3dfNv1vLGVbHL1WAKZvoJQBqbLvI5E_
8bWTnlOhkyEd1pyBCebX3WkAtQxWEc_Bo7ZeK7MrvdyWlXQeZj7LF91d6BeMwsQmz_gHoSDZUBenfQiy2NryehGBgPHglUGRNQoqJJMmVQva6Tr0eX4Hq78b
-s2jwqP9ahbYWvM5QcAeAzxBxV1oRus7hg8PwY9KWCbS8JLmK0JDNV41qOslZEkkEBgXYj3CmuiYi7RLFNSGLVDS9JHKCLVhw2iAl2WzdhWc4VDS-LTL9ILq
41bt9OqbsE84puNYVbJTI3cx_OY0w33eAcZv23GnPUZZMedcMPHTQguycLuPaRhAIuYIAp5RVSXoUOJ-5B5tkreD3gRXeteCoFzcJILgIpKsKPtG8S5a5Q0R
wngf9V0mrGZkQYqJSDMgp8GimiPCd3nLgSNlH_y0hMaqrYAajg3ZhdRJ6YnSJKTGNv2jAAevO9wU1lEFkAFz0FdwI255vgxOIWULEYDRZMALRibKmV1a0G3Q
LbrPtRJARDKL3TEDcA2gO9zukO072TVqeIXa2hyysnkkM45vPV8nHoRUXWeRx09VWkWioRoTHLvgxehaNNaoUAseEEjT5xvpHazR_LnkHm8g4bUi4nR__r27
ODwTrKfKIthoa6EMF0NfQTqoxAhsQDzpKnvc3LV2mbqQ0VaiPqWTCLTyPEnQ8UbPhWmRxSAmAz_rAS9PL_d_Bge1PlN1bPslf65NVHECp7HbEZScEtCrx5p-
55Uwo9Uk86kzQ3rrKwPUTwL_ZIlfJ9ACpkDTq5_Y2ZDTeTCLKWLtQXOysGUlTwKxNQdrzMC6oqC7czMbVL16nolbNr-vFqXadddm38lF_HgNp8CyMtg6Z3bT
KFdX0p5t_VegTSxr1ySExjKkI3Bdw9xQnZP_tSwNsw-_5WJMUSdkZYT4X9vsPNkg9IPwbnfUUmzGo7n5w3rdMAQuqcK8oV9mpsPeJZME1vOuliS4IU2iAtGC
ESNzZxoqWvQ--LFtD1FaPGdD0FiSLohIP4tAo49oU4FmVTCdKbSEkMJQjcCwxQgCsT7H81f7D7PuP0_DsVA1ngDqzGDgiWizwKfb7nsyxxGEbJLVCF1k2tP1
ArjPM6orB8GqpLKk8mgTlVAGaeVmPiLNiAPXlxuhayPRVtf94rtb8ybksBj-MSXNbh5cPVY9zQAFKqUzbpaKlnGnpLLvPnSrcbytRH-KXg5c9Jqpvke4pybF
-vI3eyT7An-uBQN9hif-vistaa9ZGMJ7ZfCT5LlAuhWYAy9vL-FlNps98xBqu8BCTAdAaGjS3SkY7qxttlBlAcFwIv3pNOtBoaRhao-ZQiLazQkYRv87cUIA
ozB-YokmF8ZLLJMHhPbvBJFVL3l55M_4KNuykIV0WQjA-kNVVDYDggDBl_coSIrSuOGhXT1ukpzpLKWW8Z2y52EXcy6OtsZogjrHzYJ3DnjMvPGBlNBZWwto
uDO8OGHAGSYeHe0fYmY2eL_VUdYvwXVHTWzr32xuYZDCV6Q_H2rG7EYmF0Ci2JW9vFk7Yr7BJ_jsk9pvbYc71N3c5sNJQpZrVc1Fhx12lI7OqWjezPRedza3
Rrb1lIrs_XnuooBhv5iMLNNBEZ-ktxASkZ7zgcvq_rXrWpXjkNxtmmXrmqzMx_x7V-ce-Lh9ZVWzbUnUL8qRY5bInY9Gnzm0yWHGb9kRVm4
}

sprite $devino_l [300x115/16z] {
x9hRagCm34JJkbX-w___swrCA6GdDYpiVQ6V1XCeV51hsauUKzswTUlMhLktJEMfzJZiyhG6fABewZdn8CaQbQHfI-ic5Tu0WNsnSnE8byfgyXo-1QyCbvPK
8Ucs344B6OR7BIba4VG3T6r7DCWR5fIiAlq0Y-8Dg9D5RbGKz51ec7pmHjKS2tjsRwVasgW2AmnLvORLhWshHIM5Nzg8KaB6LM49IG54L4I3DMAdSeHqNDE1
XQIxUzHIWY60xaI3F7yjmTbeAIWdjrZ0IBqWAwtiXCLbiXrSpxdm9-s7uQK_K5RLLUKbMnWf6O8jM76gi2J8GScUkutyzh9YLIGvqh74Anes4HUv62juPoQG
f2eN2JOBwsAib1shbP9f8UjMQHK6BiKAth42MPzoUORv8EaoVTvA-LEi84_XzyVGcbuoaW8Wry_pheHWu0-m-XDApsdRhGhQ61LaoFnQkH0h55RIC5qLQv1r
GWIaNeaLQP4DgtpEG-gqYI9OyDt9iMFrww8bllGhah2GaiiLZ7Q8fKuBGVF4N52-v88XAuZofL1WDgySohy6unBJJH98uPUAu6IxWWGDwqkN4Ky6PgJtI0bJ
XW4h2QRoLU5r-47zPGB9bUjwX9NKY1QKZHIdTXY-OeFaVy41q5c4nouhA5k5lBE2LhRA_oIQwDBp93K1Twm2i27rV6Mj12VQrHFHmjd7ReEHLSyqTzXgFq2S
TAyzAutr_CAroWeWoUL8aGchAaQQOBMQVhuo0m3BqrDD9ujO7j1P3PDlmnp3oyjk8iaucnP1Rq15kpjKa9npHbbf4rPqkhHt3RnjfHZo3HxSsKqJsOB2ISLi
pZeUtWy8ZhU1P0LF7dbiOnCYos78YewEAf6j9jz8mdASOOLAokj9TUgba57J9tOTA9zxPMsU-row5pG4vCs2cB8A6M1DT0MzKKWvm-gXhCI8LSxnynJsOgNK
Zxu0RrcXyBqJMewycz2oviOUVAGgISQmUfEUummhLD80dxA6yprtmkeEAsLEQEIEhAAKJ4s8RFmZLZrpRrb9Njc_HZdAAXjIrjMuiAIxDEqqKSQXqHedBTXV
r5m37mI32QiybPXZaZwor8woodbP9HNp96ReKKKXwrwxKhmNQBAoILsLzhpq5Zp4QkZb73CSp0ovwxukH4QopmXfGjh6pRDTJLWj2njfz9faEYsBB0rzbDKe
JjcEAJO3aiGB5atslvY7aJHiPr4PHhw65JYJzc3pRZZ1QlWSUfoLaUXkNyc2MPLOkmVeI0l_8bOFouDiC7-8rKFoyr8O2YZfCrRL5ClF-weZh_unLiK_f2sI
YWmeVvYLv9_swl8LqrmP3l5AXYufvYWhVB0gs5pRBv-Modo9Vw9VzGrhQQd2AiFMNbJBowLq-OwbCyf-Rqy0GwK9CpuSPrLchCenLiP0iff-umodozAeM1HP
b7kPmJRobUy-C9QycmLsWjKeNzd1V9LLbBzGW9JSHVdyubJ9M1EJfrktSlkyzcL_lRymaiYf7MMLcUtiWZ2DuZcDR-sSXvR3A0n5vwd1Llt_t-uaqOb1u4oy
9MN3EzK6RBWK6u4eBBv9Y0Wd4Qax1Lh6LkUCs_MmEnzCjizi9qxFO4WgsZ5M8nYE5CV4NgWhXpENtUyukz7TIrx8VIpR6Iu8Z8OvJhfsjZHREi0g3GR7ks3t
LkaDhVW2gGyo1jYs7AFyE4TWJvaaysIJIH4WUPehNMKTPXMlxTE3euuE2j8PVZIU2H1RkSgakfjv4vT_NgA71ek4oj7LRvN-MbD73j5XLZtmijb5Is9_f66X
pLh5kCeKvQn6JLqroR9wE2euISpTPXPBLmO04Xs74NX8S9XLhhGmwwSQF299LjmYyt9dCsobEof2jtzpEsTGqyV_OWMhfchci-yYfsPrY5N-bJPLAmdL4S7Q
hekISjljOkjskDtlP1SoHinnTYBCzkKWqXvdLNVoaRoC3eaxokp5VbmCf5YUFq9B-9H-t0m4bgq8X24zNNHZJn662BCap3gyvRWuBt88ff6exVzqTBCKRaPu
m8Ogu5zu2wI5HUR6OwJIVxxuwqE5qiBYKfGcCpF1GZLyvAHsiD94cIJYVggetKu4zG7MrO9A6gW-szbPkO5bb7ui6F7FMpyRLQoDrcP8geNHDIkAHbMMAtti
qMPiSoP3xp40gV6pk4JjwYUfM-LjLLEwqAKmnWW1SL48CGUkPrAKaonQhan4Oh4khEx1S17gQOc7YdaeRH9EMhXQrGNgzZnJrBwbJ6_DQMb9JwB5uHx5piIF
59srMDqZyTWJT9yMgx9OBLQBrMArMBs_Vjvf229MPi8Th01YbRs95aXKbMal6CGYV7DD4CIgZFQQ9VBs8F7lfSR4kvHIkScBrte9g4wupGeQSRqwOsf1YaUL
IR1Sir2rVnENSjcgI1fvCOeqjLvI21x7oZln_d5R-wp0DnrloRhGH2idLigvOxHnB1ofD-79h2YkJIJ16baXMBZ8x111yf1mF4imyHzcRjwKMF4v9-MQchsz
OO-2HSniKHHcfjOPpGWdTTut8ojey3cB0db65S5S8hX79MrYfvwLgZjTKeTda7StAZ_nEnZ55oItkJchH99AN7OagUkGjKzS6HtOWjJg5Lr_hUc6uedVmPm3
S5F0n8fAX2K_p10FxQoqXKzzCc1nOeK-s6j_ez3pM443HYe_PgouPn7ToYZj_iwkFdCNvtmdauPER_0JM2KoUGIc2IlaYetalBzftRv5kwU6T2CG9zB8ZWlW
9xEQl9z7LfbhHhtdV8IpzboSKLjyl3ywX9x6AdV1dAK3h7IFrKs_Y4o3qn_8U8EUooh6LxIIG99PNG8KhQAVt37Lz1IQZbX9LPHkl0ghkNJ2Idr7j0NBRLOJ
zw3wzgnymgh-0rROPUNyVsJbxekLODGUAoMCQeQpmwpgUx7YksnzOyCvuh0ShDvuRCSHLlnFMDd-FyExiDBxMUNpdh9uP4LgPjhqjyaHClhr1gnIrTx9old0
YSXSqsZ7apdEkx2AyjFF_-tp0GkseOODi-ETOtsICzXBiuhivwzNTjgTsnagxPM7wynVN33ElDDi-cLPvVBKr5XutoO3xQpa-IXh95DdccmcbsP4jRqkAohN
VRheBBjn2IvHeiIg0QkCTis6HnjoSymReqTdX4lQL6ilo0esFwR9Y_19vul2UsiJrzM5ayHp_wKsU1ZToBPGwVBmWgpc9mP0YtSotb_7OVDELT4tszg5vdDG
-j12No_D2g8b4o6nkXLUg4NxBQKXVSXaFEHOourG4lDGqJwKyvj8HPJJ3U47x__cau2kY2nopaeg7axAwQzn2VF7o_7GU5E-CuloVE6aVobo2itwPoLUMbfQ
MbfQ-Wi
}

sprite $smstraffic_s [128x128/16z] {
xPX7akKm34EfdB_lVzjP_r1358fjTT3REu6G05d-AeV3uN0uk3BN_vdTlrrKrOkQ4uY-TAQJPyRI6Ku0qaBeyaHP24q0oe98c6RFHD79wmbi0dL1306O2w8-
sG-yg8XEd9W0aPZQzABJ6J770dshunanuq9Lqwce1RcB54WnFUnR1LRCj322w3HKJ4ArOMb1vg8iEcaIOkwseCnbaKEyc75ktWJw_JdKED_g9520i3c7vhVA
eR0maYWGObfl0euHqzda42zcije4zkSGBYRbMyCslZc7zfVHJ6sTNvL3xUu9xC-X5GZVBhzj4y0jw7QNqSpaKFkxPTH-4sXC5Uhtvr3RRi7TFqMu_gGJgFFG
meYMPPJmxN3c5hGlet62ObBzoTA2ctCeCBuDTXPiJ7_A0Z0X-ejg44LqmWNnR81uGLJHcHV4qwUunmK1w5ylY8TZBX85_4lwqyWUg6Og0_mIPcHBL28po0A-
Sn2LTK5CPcJ3pdo16PaJ3Gz-IJKt7-yZV6GgwSA8jFdibpu-CfME-eWmtt90xc0KOcIFA2gBCj_MfO-FR6_kLBFSMRyoT_08eKPcPpvlRZu-GkA5aUnonrdd
3kyZV6IsvhFF7Ro_q4lVtdpvzjoPVExOcw_lhPp-_lEE-tcLyoBEEvPBlubAGzNVcplLjdBkF-_mcnW-ijzttjbVEV7zOk-lZaxaZcNbz7QvmnnHirtkVD7I
ZypIJwJw_85ZC9erqIdC9jQvfS_RhxnS1Brp4eJyqEzKvOK6N9G5moUD86-4fF7HUuV3uN0u7Fu1
}

sprite $devino_s [128x128/16z] {
lLldegCw3yn8bWkGyFvF-vLpSpC4Mu3OCdzsJ_EeMxQSnrtW2u-_24Woix9kKCmiuUzmhmTGmPyapsLQJz2o_XaHHDUhiDyk0gIk4JJ3xrGzrJMChBzBz_BS
BsqfRGCDZcj-Hp3YEzwNPzfdErBvSpQGiy32ILZYbzWp5vhh8AgnYunQ5K1jsqYC4Fgg9V5-WKYAmG-otAId5bF6i1njDI_VqPOAO-PM56ZhTVS3Sn0OiX4E
ONhZte9XQCnSlZXR3uDZ2Ge0EqvYsAKqnqV8bkvbdU4aByhnmaed1kYNV-FEnej-2kBS-TqFKWjhtp1SiJArhhWrXIp0o7gEerPgjBJ8H0i4jDTUSspfNt8v
cfVh5f1bJ0-jF_WqG95s3_Mg1V19AY-LALu0k1e3nkNxT2SAnGjQ85sY5sSdO4cC0bTAiNwq1qH4T4qg8jRr5M5wMc31wOwNSXwsDBM-tcL7mlJCWdH2xo49
y2cyjpRqwJXqrUVcNvMxRHLBooB-Jtrykc4QCOnqL0NoYVfls6r-SbZO-in8umfnW4dO_oIWFnkk89IhEVtMrDga8DwzxB9tKxtdWfdnEpACAfouJ5JWLnfh
wIhOMLgXi0V_RdhdWhW0DcAI9tKSyFj8jpU2FZ5PLZlPV1ZkXU22NgRYd7AE4T-AEykLWwMi8vm5Mdv1WDH5GELAfvlIyjDumUYLb-5E1AGhBIT_bjftsoTs
gn-X0Ig_Fk2lR4b-q1r3WW8meXVfIoyyzIlyOrXSWFgbhHpm9pREnxbH4Ty5-erNlTeZtafn2z3YwEfRzgBFz-KdFoQD5k5C3kV4EPsVDkIE1NJ3htunmtIX
nCX40M8PKB49nlSI7V_vmhXXWPbglMD1kmoWQVAPDk632SsAztOaIx-XfeiLNkR8LHkZfctxoSmhZNtsuVg5aOGoSDjFfsu1kTvaC8WHEOnXmu-kqadWh9-3
7P6zbNt_8JxUda3-W4rPnJJ0R_-c64X71InIskNwJi3GDWO2J-YWIe45kOkNM_nKmNOt1kLoI0Tk1spFp-sq2Lkl03-t8hliBNl8Td_JrpyXU8-VEI1NPmlv
pM_z3GNjdyAtRFbgh6G82Lb6Na9-QXC8GRbQBdVyo5I0-H2xuJat02Q7dtKq1VYZ1e2j3Z_Fvmst-77bij_MZd_jhzTnWv_sApYt4UEV_9Ik0ItE3ph0foSo
wq_d7PCR_5p-h4Zjwb_VpBpQwmQ_SE9srAosvl1J1MVyU7NUf8V36_lK_zRhM7O2F1T5U72PZbhrZFJTzk7a8heY6e4D1piqs7RQG5gvFyYdzU2N7L1jyW_I
E6u1lskJyd6dyWJAHi0n5T62_9DWh97IIv__FJ7sOicVMSXJWgEcjIXRkVbxT2LKQUWjsGvOKsZabdgdQTcFR3SkAYDlJUnyc5EX_6ClAFDhHy_p9rLrpwVq
1YxJ4pNPu9c4l6WT6THBp4pX47zQ3p19T__0Dbzx_hhZDroDlSb4s_pD_ahONO3bRTkQZknF-mNcAp9rRw66zXHcu8w_ih7kdzdujMz2LqQhe6lKdz_IwA00
9WnYAgahGnkRhIcy-qUIrT4Mr6pq-6wfjGe0vrWXkx52sXUN5-zVQQTPBWOoaLDI8bbTH_mwFYVLlJrIzqjnk6N3lt-djt4mzrZcvJ9_WJDey2PG69rQOD-5
72d7152kUZX_uTNBVil-wK2PKe2sTaq0CtjB-r9t_dG-VnFLzEKjGDEyHZ0xuyohyqUqlRmGiLBhjnZr_oWcPL_pnzwV-Usp2PoE10OWglbJa0G_wCTrubry
x93y2LY9NGFOxDxdyqKUlBRPDq2DFnxijok_bQ9XFD4qTWYUVPA6qDi8VSKwSFL-7TE1Ay60tQF5BgAovoyxl9pGfsSSn9uTETTsf_UvrRL0OlTw3ZX6bdQI
I73jZ19_mOYhxwy8TICzFWeeuVTd_VE_-2Y8_2dy_guN8FxtzAAEjAVySG7Q1VkvvvdBqnaKJm1vdPz264GjzlwK4FU1gqoN1EZjB87tjwJfwq3cmsGVqktl
rgXzxFsrE1lRaG2sfpBwFlgnZzcSopq_2C7eeJKfKdG7DnaBK4yUH4JVt_lN2EgS2XJdwikyTlA6kwYInW8ONFLVe1NfhnYahaCdmBpUaj9bVWQ7gHm5wiA7
Vl8OvDDId0p50z7Ft_Y9I7_tts-AGNThGjrflI3wJnWP1X-xQe9kavnUcx_It_ZviwpQIvQr--NUQlUX-ViurmJuCK7RVG88g2lXzMjne5VBKaeGeGJ5akN0
oyWOe6KD8-dZDq9g2t0lZDNV1Z0G7CGpBYx2gHLA3eHy710vyhd8uoy0OcP6TzHiPWOy_Yf0FExZlm
}

sprite $tinkoff_s [136x128/16z] {
x5RfrYif26nGtANU_stdj3HsSdFkabdopSOlGsmeYm8z_gtsl_7V0qQPuMi1X4L41h20y1VnmfY5ZumXYdY4YaPVWYD3eGETZgWOWE9B2A4nENNqCtcSQ97H
FuqXbXGIyd5Gf6Dheq9YBX-LXWBG5tG0FYoIZ9hZXId4G9St3SJFYWFZX21TOJRhMQ4mFosHWY0DmAWvfPJR152Y87qOXq217eYS89BLklJfMQfQQ07W40BJ
ybMCuzEMUFLl6wjrHithzoTKIiGIcMxcPU8qLHDh3_TEukXR__JHfLWshdJS0IqYCN28aXg0mjTUtvh_R7v21xINb86wHvaAFTALWKwsx1WfrG6W_gcSYABB
KWMwtoxezA9TP5yfBsW3a_z4JG92bbt3dk7rsmmyWVr5DRZr3mD9yJudecTlJtS9tvHG703WFzLN1NDlgk_BnIfWrf7SkLVXwf4S35Qstfdt1IGRIDrylSkD
vN7rtqfey1KD23S5j0TA0y0ir2sbVLHsTkLTtl6kR2i6kjCHtDl0poH9CHvwEIaVa2SS7igyf6Z8RxyzgLyVFR2P7gCtYnuwCfET_15n_1RIkK_dUuGKo1as
qpaeTbcMQvEiMmft3_6USUCEjeZbXax6pHisiLuJw5ao38TFIhMf6O23Kjmu91robJyMeF4T35CawtAbDmk3INOiu5bSL1IQrXRmgI9PED94F1AQyOCfJpK-
pQxdWFeM3iyTSidPWpeIB7BdURIAUIG40j9Pp6838z7J1ocNdDWmlVb-LVt1zhZ6H5kdJ-FaWsPOhPpFFmV_wDFttlCTFveu0qkeurcd14HhgUzRVlFX6D5-
X7Af6FC51trNYNJi--aTet415w7jerJ84gh9BppXY50xmTKqaUvmrsLLxkFzs5X48bdGQD5BRoMdKWSqqmD6df0d7CKAvUEF2xJNd7BfBRFjDFbpj2JVDQeA
0FCyji099ewIqlGd3Lyl3-eeZpXeMa-IxfqTFILX9X_1IyvjhYJv-sGeHisbwPAyh7ZEAthmbH4V1e0PwS91eW0g6z1vgI2DkG_ESpqfPIN9pQE_MfWerq4N
VzozchB3XGOhIWNG0RHhZWq00rOwBa0XVooswm0MdG4K8yjcxek9RnZGR260XQkXqVq-vEklpZPlUqMTM9bb0ZEUefgR4XusIHcOGkkUGR_2Zl3Qg1L8Qs7F
RaeAr7GwTCezISzH6GVGpHSxp4gmuoiM0UpXpaZBGwa3GuxrUUShd0dOZAAK3ipb2cgy3zzJ3RtvHbY4BZXc52RWuhaAfjLqxYo6eMdflItVOe8kUhLdxnq1
W9vSgjbSbQygPfVF2i85CCQsvIQ-TFr2QFKLUnyYq_Nd27udB4e609zj4pcG-IrjSbAv8zutVbw5DolVQRa6iyxhsEnOKSaIOqRhUI_6FTi4dHntNRyrNXsa
mM40UVLU5-8yi5_HRVJHkq-C2TimqLUu6uXNATiGcSup0xw76hhGQifEDaezQhnXo0gIlHsz_R5CVTAg-8badNu3IGuaBL-OgxYSO27zAymnhA5O8T_2OBL2
zNxiiDSkeOvAmRW1mfvQrMRzVimLHvwNB-YPSWBfkMs7pfujUxwrOhPPj1RodEIhiYVG7RJ8zMTrZySZyr4PgjqLluti6g0TjLfpsV9LbWIqPnmqp6D6-mZY
507fFfQd_8ub9r9mYyCGyRDvK-qZLq3usImxUMmVigmU-_im9llMVJZJ2U75xAW3m-h_OktgbAqPNmf-QzSwbEHccI0Jo0pz_c_xro8XiTpAeLpdFttjfDkW
Qcjo3uFH8_pbQEbskNJLzw-8BpkNF9x60qswDTKxsKVqPo8KPzWvmHLnr3jF-zRWG_377-z31OeEata3aefEYAh15WrYtjLe4ddiLBNTJwjQpsw_JK4Ldf30
B6aegBaOqFMB7yTrA1lePP4EFjPzahgy8GWjNabExqM7NZHg4sRnRSh9j7lQxP_-2hSQhT5IYF8TC2mYFYGRfNmYTxsAFMpn7d_H08ACg4d-OxUPqUaUsg-I
g7UaK32Wng0YGYwW0uUCiGXCbKtdeybkoQeN3Qrjy7WQdCizQTCbL_XAlIv6E1zdxzu9a5Fqv1O8F4qU2RBmY3pW4PsCXwC8Jppgr-d95nT1RW67b0ewtM6r
8C6vvkViHfzuX9E7LEDVu17FY-G-4FSZhSIlIRlNbqkTrvzvZFPucCYE6uiyymYJHz5P01TG1zyLOCNhpY5_uK6Jn_0AopAkDOy76i8p3pzvcAmrUwjUigSK
6GD9fItu7Qyy2676pcZluxozVtuUL5zlR8QyUnGF96L7udKPq98y-qVi6hld4yEL_UdFKf_z8uN5yQCoETOAarMajDewmY8wI3pfwaSU8smFQBCWSsAHBbzu
fBFIbEFXw6bmgzM0ocjbgSriycZ6ruR5CUh6GtFAY5RuWbQWQSDWK9jiFEXKK5LMASRGp5hPVPEOqkdvi_RFSYaRZrCrou4dF8mTWy_nDEiR3pqlrPstFmtE
3ttGoIDCnzdht8oNWXR7V7lHw2_cX3dJzaeh3mE_otQqQS8Ryc6vRKKmu_hsZreE7JVdb5ACCHrABq6lEEM5HqP-ZqQagTK_BUnft6vBaOAkxpmg7JF22y3L
gXIZUQScayV-U9sYj-bu7o776wb5oBuZrPN7iKkekyH42LMMuR8UDFRE9FJG_M5bSi_kGTqpv4il4HSUKiqVINU5LgJBXAHjyA2yqt3PE6UwtN470ODDTUvB
vTEEodV-q8PkgE5jUGdp4a1lULtxLusZ5aUTPtdxYdJydr_6j3HqDbbDWxhKbunUIXjzMF3AGsuemXomrXTYmneKElorPUTy7LVGZo8npzLLid6dVdLeqL1e
oQUQF8keZfrajrODGNZdSIXkVaRpCS_9q49odBhq1Zx4I7zcChhcX3QIRqypV-mGZRcsghClMNXC7MBaxnSEQmnUILQDPrLFqjr4iCN3ONB32nPbnelm9uZ8
yM_fUlDOzy-zjcFEpksqD8yHkgn4A6p2IcvdvDFMiA3_603crPOUP4w5VXc0gItXn76kL2xuhki4VTUNcduLTlDOrOFGQSivjmTzc6XwFEopfkJ5JuL_Ylh6
W-kfVbZywfYDtAw-p_xEWsw9y2kFM8CEj_Wr7gJzT0JVvUY1jW0Pe5lPazCKrDAbkvN8EmyfQDbhAV8BF2JLANHIBRCb9JUWXhGQ3ose9WDEI_XfnsFKwMQo
y61fw30WoGzvf6PzFHgYPxuTEdHKZOR1Q892mq2TDg9shwP3CG2wyc3j9THOKSEFU9GZvLwcRV4IX0m3Upz6f348EPxZ84FMT-F6WmCY3SD7-H4FlnwAIMr6
HdT46gPi-zo4t8F0ib6dbOSY1pw6ZaSUszgOv-pEAB-msDVfD74DMLlgxTaCCPtznGEFVSrNvWt3fFTB6qKsMTX5zyOZWXpHcVsVuwKjFKQevFQP-Hboftm_
loY7XhdQ9I6aEZvPKPvvi27EcvZSXm9_p6CV96Cv2dO_lhZ6hUH-9iA475J4vvgzUf6Ln-Y4hFXXPjt7p1yZtu529HmR8cEtyOWfdXjZBXqlM6qZ4FKzZmcE
amavRkFTpo1l2KwETOr_uo6XeUEIXvc5XOb8L7nlilAOKqWiYx_-qZAPLX-NHlDWn-qVaaU2_2G5iTDUPFAuUmUjMshurQEb4rhE3St28o8woUcqowvO1CIR
1zbXvRMWivdxBHvqdRMY0d_pQCLve5at-ZG25UZ58o9FmU7tUTJpugYyyJeOH1rfrBXo_EnaFqd0hOjZgyBIK2urYGvBnz-oYyweIWUVGCCaBpFR8IZNwgin
XtboUnJAMcU-6vPHGnp9QFQYo_nRy2j-EZyrkrFMKoKOvNfC1oDK6j1pW7MSQ78UcQBU903-Yb1TpeTiWzmJvjZfC-RN-CeguIngkPcBI34rDEz3Y364TgnJ
fQDK94c0NAUtwDfN9Da6kKV4qVHqe9PfeAiq4Gx3I6ak8invOS2R9JCcjDQ2A51t2nXY1ypid6H-38d5HlD21D2MtUBPWMMZi2-V4Zn16Fv5hs1OP5KmFF9H
8s0v_fJ7kZSBA5jsOpiiuz5waOr7P-siq97eK0uTX9P-U6G0-ltZmjGMow2Vy_Pu8X5D-GrIgwkLiebeFgKPcQB-N57_FjO3jclFe01QKecwZJ6-1xRihFXa
ip3URH2je-plGpiAh_tHF4TWunY_LrMPqpOaeWGC59hVkOSbTdy0QUXHQOgFixTVqAAmfeO5nRyfE-mpaF-0nXp1qMfEiTyJicHRcOItdnBVwsUBgLIRvmt_
31IBtOS9w0ugOH6D1I_aeC8iay9eNVrabYUBFyNGVho-xADrpyd-WmOMgpZ7-e88kM_0F6wqGAOhhqT3tJU3ciMEvEc9foze4SLzDr8dydOquJieL4DLOgZx
RXnYikO6jF3Eq83ZF4S2k--5fEkO2hRJw0nCSpJKIExxu0sMvMHqX2lJ2qmIoYtuEoqTLRxDHtr5adlY7IhkH6_9toEO5XJzncZHrgkEAwlat7WMea8ltADF
QBryjuTeHe_27kdpWM7M34lYlXySEgnz30b5xMYUtL-25hIF56qMrhy4_v2fSXVtDz4GwFCnn-3-9aBfXm8ginzJ7ojWMTtV1KkS2g-TCrqDpExV0manvPnJ
_DOO-GV_u5y
}

sprite $megafon_l [300x54/16z] {
xPe7jkGe34L5Ze_zBtSgu6Ev1AQhloVxpdGo5SH52DddaqJRa2hWY4AEJj646nKAsWj755jhA7wawyQaBcftzG3nqzQDojqKTzLj4UV6epNfgbCjSUwachhY
gNMZQsipLvrCJsuCsj9LApJaLjMiSDKotQZQ5guwQVe9Ij49VVI_G6c_w0gUHlW2eBXfqrPHnUZbQEly1yvgkfZOrguwC2J9VIoTjIB8z2TY4nw8Q1yaInTY
iN2rgE-fRKIIE8WDV3cse4r1CHVlmBMhZXUvZxEiKrMCNav0EmMUBiAthrn1dRo_dExlsFNvC61pQvr4KyULMh9TgrhBikuLXVVEV0uyiSGnxWMHF0DhnTnL
2oSsOEc8WZ3fqQPBe19ElbALqHs4NQYISPbGm0TBP4T0hwwZAaDEBe8YK-QkgYXNZ7oMjEYjtDnLRaC2AnP2LjskPkyUz9XBV58W4rvd6G6I-XLNPPYl6bDN
pGvTORX3os7mg5QwqfYxujwXvTbH-ZL_E4XiuK6Vh5KrQrSYFFH9pbsbaIkaqL5eUo1b_-XyuigrCrTrcBvvJnpXYgrMdgXY_fUkVFlQ5OQkx9vOOYBX2bSE
Oc9iRdRcgikfRCUEAKjNkStse9cwCYDNsm8wsKv02rS8_eYZtLM97zWzGGgEwMlOH8Ukg72xVRIXfdS4Uvc7Mxd2yCpGfSrTjJ1qPMNR4BUufIiIxAxS_FQ-
RkzNnxV4kQl02rRT4qBK-h9mDGArefsvIaDNL4NMeL-vmbNkJjoUMCo4dxkox1MMxLYPDchkQi7SLHcxyiSgoYvSu4fZcqxj4nDPCt6bsMO8unQnik-zs5KT
krBugBlTa1swKaTMhkAcVGlA7roPkIjYkpIBbeD_I6Ikj6BaYrtjimZ7XhhIo5Nz89oxKjYqam8FmYzTAIQYYFXvf9cvEj9Em0CzTGKrTgNPB5XN8boDYEUk
0llapCkpN-v1mrQmTYUSNN_fhhuYzbtnXIlkmHyQ1hh2LMKPQzdCo7OJSrVyGoiRu_o-gy8qVE6Aps8N7QzmvGxVMrakAIpwgnu7pFMkvlS3wtf5L4HSq5Uu
AeSv1hQah5EHhfXCABO7htMbwmCiyawwSdkWZdcNhf0-SCALgBq8zetZNLBgCQc9goJZAEjwXIEdhamx8SrSiUQ7fzYF-wiyYxDxV5AjSCKVY3b-BCpEmKNF
WDzm5IQkUBDds5BzpDMy5i0SdchL74C8kS_166DTmh5if47RpfgTrRtpzwvW9gvuyzElkYjSfTC4rqEJnws3OzBbuHQ4NRWAl-6A9gvuKxKv-w6hgGnsS3Yq
1GWV7nL7MnphPttZsjuQidCPhI4v_vmhelLr_gpl60twIanT6Vl1t5NV8U2mEQzbmOldjDbGHxd2itJz35dcLPzdx9bPjZ_PRXUkH1s6chbgE7dMvyOxvC1-
YFGAFWLPyog-LxUS7XIm95svyXDNjGUQwOdfrXtwmDIL1M-Q9guwIrVp6XEFtw1yhdXpoCAQlHBxRKoWfIk5iQj2Bshipi9s98LpLrHuEP6kuhUkgZoxsBqd
Cw7D4zybcYUQFb6b3K6YjIkAPtb5ADrHxdbLQU7AWgMLT6NmdIi7sJ-AUy-El46Kg8nPzL-xKZYfLs6lL-QrAl0hL-J1TermHGvVkIfyxj99NRcIk0gHL9f-
oHKvZC_1P6t2KxbnfRt_h79zAPGN7p-AWSgZpNXIjzeI1xpV-CBIZgvl57rIwWjBHtHvuUW46qklR03AiQILDyI9-xKypAjv7xf6QqqSzOQ-fxzrCV8zIdVK
b--h2rUYKxb_N7JjAj6DmzeLhzQtBEvggUgM9Lt93NXZgd0rA-itAk74LR74kB454rSGRV2DAnYuga6HvCR42kuAo8vct6X3fF6af60KTMx-
}

sprite $tinkoff_l [300x92/16z] {
xTg9Sk8ueq3XeyNo8ald_T_sbi48ICXDyazLptHtljam8ejFIMxXWV-87py2N_IZ6VdK3xT8inaf_t-m7yckHdRLoaT-n1XiJ2q2TMConiHBFnOrSAVAIp-2
Iu6OfdMTKmp4oPdNVjGULjNULLiiye4VILq3LxdhpaT-c27asje-Xq3eCyz-X3Ybm24mEMpdQ0Zdy8_PYnqWT5rZ2274t7K2RlNsdroXkySGTWD0TsA86W5s
OuYp5lvornxPSjP9t5Kh1-lrQEQlD3KkkW5WbRELhhTNwDbgy_nFvf0RVvDqBg_9nA5j789EQikXgjlYV3uTEVJ6GLV-8gtR0RhdSUL28HNLBSDiu13FLhC0
nSN0Hyhy0h-nP4bMm9MBnS9XVrgI-rYPN0GBJ5RS-8Yly6-AM-13OUCJip3fkZXpLUq5A8Qym2Ba5JiGgaQkhCjkXUPlqshf6ZxiqFGhhOXLNJcbtHsY1SsB
T2UiKBHmYdezcWs_HwkWVjpAmwUnvRt9XUWE-xI8cUn6iFBUAdzDgsBalTv0xosB4qbUiFEHvMhpi2zNltCht84mSOhJ-UHJgqL8HY1bJZcTEurF90yZqk_P
QffBWiaLO6rrNMgt1c0rmMuOhPhSuxclozPg1f8xX59A_ADRPGyjChi73cbkBG6XkW2RQpXR5KqGD0DiBfcBsGQpX_M_qYhb57Wl50zJu8MGFEJ8I-LIQDL8
LWwRCy2a1Og79IoULMiWD3U0s7e2MDsWwoNf_hLMamTE7jhzLV7n-GsWUk1P7yCmUwXS5A_MoAEqURSbdgJLkvfvPxC2coqH5esGtJbKTqZgJ56RwaPiEiEY
2Q2u0jeIR1fWqlYLLkNnt7SF_ODM5Q1zsAe-rWddznWMXjXzrYD3t7qZSHT2B3e3kmLchM6y6uvQY5LN3elgFjPi8dGBXsQ4fTi2GID4hIc6xxHA_kDMwI7L
xAETK_6zmYdxtiomtkxMLJFiRa2qXVD7nx0yVhErnOTpxf7gScQSW4aJwFXTlzFABxJQ_zzMuM4g99-j7wVIwU5t-xWaqPN3R87c1CGnTnfqxUFNZWSELUsQ
cQrZmmgXcyOkAxb-ezNkFvvNZ-VcHI_azb0mUb53y13OFH_SK-y13uJwTXckBW5cLzXDGBIUgUgvNs3MyFHdwMu3Q0QcyVBrN8tdl4pAbrk5w3zjTGvk3zzu
V_kutKx-RFLYS7eup-IXCQmUrjj5AfnZmHte4p3EErPJ1cPtBeotApjCpW3TG1fd_TLM-8zRRUF4tYvMpp3ZXuzMu_J7KpEZrHXC3A7iQnYtN_HC9S04Zpk8
QXnZX_dnlirs3dQWr2toZLRrLQiKhXvR3Nq9Jwrc3_rTtl7TykXoRpKU5PZKj-k7S_39kBfivqWpG0mXnXYElpMELiqIJo46sEH20n3T6BxOAlggrV3SQcZX
rce8N3tzb71hjQlMvrOZQtjJw6bzFnXBBzivH3FWatXU_AkF2Z1sDmrWTlvkAm-bVRELXZUj4e-jvgTMyzYrFhUggcqCFhVQNrnCqYYwSb-9rLOFsrQtgZFN
6TRMGQzr8a3GE7RmtscrUU3xhNpJogTMvLkj_6AhQkDGnjNgtAIqT95BpaLjJPqPafN3xMTKESoQlj4gUOXVRfLIIhCNSQoJvg5-FAycQA_MO7jSW-sfrHWS
qZvsOwwUxRZGT56iEULDTObFZTFZFS9jCNA8sfSljHeAjE_yEPWyrD4gFEqSFQoZrUErlJst6baN3tnuROzUbC15Dih1dJDhlgQQZmTRuurkv92kpShMTgvo
yx1-jLNdcwtmq4OhYW-3_VqRpGZp-U2nrUpXNlIfLRe_1rgcnCrQWmzB47QdezMsut8a-wWLroXbZN8JyhGPljeg_EDMR0-njeS94UxF-nmct1wqfsqOxrz_
A0Rkd14W6fvQrOfJJhdl4SYlMcq0Mmn6xbhdYwqAtssrUrZUlyVP7lgK-zgPxdlB7aQhvFqdJHvw6gr2zv1VtY4tiBzgjM_niXXp5M9zqQfl01sS66Rp5rjr
ljpgMHYjtbIfNZLzlpPjcuVj75sV1rSFwpxQNurx2W78mhIyQDNMkQT3DXC52ElxUHKQj1qWZAt3rrg5BxRQVRRps8hvzQvhF0VH5oedNzYvIqVbtGmi0ZiG
dDwqSauNgtcs0h4_jrg0AS8gW7tRTU6BhGh_MwkTnrRFjmj3yq7a57RVcXcgRwqycMkxjgeTY1cmFxJQcsUpbFAgkUz0h_7UgXY1TLm0RQqjaI-ssddRAdzb
3UuJRrk5nnESNv_mr7oqnQV1_SF1mGJO018m6U-j5WyjdnChCMz0gCwZLMktXPTDW3CVoOV0LKWfvyGfffHJv90Ee-zuFkPqmv2ExnYvYFc2gsdTwhOMtfhN
ytgrJBnJrlDwjKwy4asGRTpeGwiTUglRjgxhPeAoSoZUMYrcJfCDQ9N_jk0X_Y__psiJgCs7UFlPAgUbGtGxr9hkbxFWhX4ehjmitG2RVsuhTy0amsGFvxpA
BaGPGjFzJ6o4nSfGjreWc__KLia8jI0GkOfQhgtIfBhb53XazxpiOtyLkmjtFIDW_LDRASGTUe7hCZkENSQUeKtBtjIsfCqbfRNUMsdc48k0aMc1sVHdjgf6
gC2oGlPsxsNYR7NAULgRFUUKPaShwDfRLni4WIL3D_0V5l-tLc6tG0780hgrtbi1s9tBIxOKOumQWRZttlPByNK7o86WyJy-hthX0sgVUIUichbnWkJ6pUvd
ulDjluT0tHR_mwssm8UiBmUJBJ3C5PX7h7CDvYcdk_pmyDugsO0e41wsMlzG2Fc3vm42lrWtdgKpO01ctzw_SibvooFJS6iLTjlO_lU9YsRuy3IV3r-Bkofl
ZGrTzL-8rUUyT9rk4ukesjiqhkrDktjEhrgrFjw09W7KMlAkYVUILkusvRNLGvzuHPUmAhzSzZ1Pnio0K7PTHglikcKjhrffMoCmhbQMfhe5NhUI8QYy4jMU
u___AqV-3G5m0KYT6yUyodbsWkhygjNqTBK3yrXQhrlDt2mVj8gVbGWffS2_fifXMRagfj4gEKL0yuirsCO9SfWDV2pvcCSFMdKx_sMBWKEFuztpM8DBenJO
pecL7rjb5nw_iCbdhIQkveTMgUvxkRye47WqrtrV0uUyJ5mjIm2OocdcLx5m20BpRcUqobFN7R9RoNcjopJbqOh5laNOolWsdxNotVuuTBrNh5QgwXuu-r_L
wsWRAxWytouE_29zvIBjX5d3sIgdbFU-cu2bgtrJBNdihpPROggSgTCdhIR7tLGN1GZgEistM9eyfRFLFarJr-MXLNIqQjlX5xRQEbTbXUG-vjLYdHO3Z-RB
YEC3MAcDWV19gw3zBD0d1UZdQUuQ86fp1lAOTe5p-A5LlwNjJXn-PIivhGco-MmrcrFRpDnDZQtVvfKLQ9nM-QGLgyRhm_dQQjohG1T8wd9xTU4kQ1oj5jNo
xxQQpZFlmcv9QQtHFY-Lksp4BLzQBKOe6S8NMuMWspbBhgqMvMgpFqmdQBOFMaMTHglogrlL1f1t80MOZ6mkEQrxCHHWAWd2l0CsebFMG6l02gJzpFX9AsWQ
G1ScVTeYp0fPzpVx-hdsNfV7LjsTVszUkTm_h3O1JYnkAKswPRNQlUY9oJcwJmeM2Eb-sztyQQkeXKt3sUhU9f-jbiTsH6z6gqNvzrhDRlFSlFz0PuAcb8hq
bkTjoIaVHzsDhYrN5t3YIdMPP_kdhL3HbTUjafQdLcg1kDvRHPt-nLPJLVU2ErUjmcvDAPcsbjFD8kAKSj50DDqgJ65Jz_NpLfDMZRnUWq5NhbQ5ei_Ngvrc
PRJoLxSQohWXqo7gTjGntrjjDHdDgUZoy4aREyDdhL2jyFhQZZQkTZiixi-jsgpy5rhHpbYRGDO-vphTtzZaFgyrEMrQxsyZmsxuHgjPJQDLr3Js36FbZHhl
M-dqr2h-MwrepW58PY1sjTLrMvPvIYcLnM9hgWj0hroJJdoZ5TeOhL3ZVRD9E4Tf6g2S4Q9dAzsujzgKVwqLczQSelNjXoNMuh1no9QKPks1RxLQJG-jWhgb
ugtuvL6QRiTgIRbwRyLebNQT_yLMi7KF1GA7bATfhgfjcSQ7Dm9uqH9Vb3Hmw3oq8ghFTo2kylFehTLqRzLrvzzgDOGG0BVuV2aRakLyqJU4KdWGvjlXjBSs
CuIbzOVZlBTzWb82f9AvAYMoR85noBzBxIdmLgns8uz-B3j5ssEk45Uj8SgZ7s4L29jkdAAQW6Pa-96wBGDCskTmCLNjd05NJZ_2VjQmnhLxLNCs06HD33_2
Qfk81XvP2RizyUH7c5HvKjGryjwFwCAJuCnBFvBJsrOxB_q8ixhNRIbbNklUjIO-yYDCPMrTRRLCYL_fnuyVF_uF
}

sprite $sbermobile_l [300x39/16z] {
xPc9rgCW38N3Zco-_zjEjT9uIpZwdzbdUizMQO3a8mPK0eLSwhgMd3oXK1-PkfwKDFqNKbfhHPlqGpVxh8FeVv3laUhjXxb3ggw25lfdXJdIee_jPdheLLQb
Vr_hIV4hzryApdeVod5fw1yNvac-Rrqrjnd8gdzQAX_Xs_keD85ie4qm0FuVOl3SoGdQF7blyuQ835zRBOpj7Z926zYwiCaHQvnDqKd326p1SzZfM7p3AfAK
vCGqi05m2ohqVGQqUPkXfSYh1sqE2WhiHasXN-W2g_HHeVQSM5imoEEv83xdcnS-gHda9wmC2QoAw4UMM4MO4flg2h9JLa06s8oiEXAU0WG688xpSjVCafSD
nW1-m0fo0oSujKLWDIwClsB5danPLVo_3QmYU0MA41_WHod1ouKaLfgO5Qe8h0f4nQmKz-AHBrd1SW4hv3mDyzcIID3iq74wNyJqkdyCkmRok9R0QkSIQh-D
a1N4KS2NTLSzDfzoIa83CEGIcsHMUXLOfVE5XhynHem1t6Q70j7tiEAkRM255ipAdx3nTRfWLLvvABDQ9LRXV15vMkCm6FdaRePIyXsim4s9rS8638Z_WVth
WjMEofme8wkCA7igGMzk2Moce6GEiQCxty-gIAmMNfEukzB3D6WDzEQimdCqxikis7tppagTB_PYpwDbZeyXfaeioBQ1rU8tMVKrLhPZ0LRXDTF-GtTMcIE4
eEjGsxD3lzk1NG4hJWuwizB82dVtq3EcmA57OQYGFi0A5LLdXKe2goRc5VNollj3BrOLmNAeqcuCxeNE7Lbr3mAm2YAhUcQrDYpgUXLOQPaLoj3LMPJHYApq
QR4NPYNLov4Lh7VdpQIHLNnw1goIoAfqLY25Ng1N4rQeS8-LueG3LeUxwJ15LZHdXN9iiBoUbJooCZrWPiLqHLOARXKmkfrNg2jMyQ72nWChEkVe_Rmou14V
gpMR0glUXApgbDKkY_SF0xnThwBUP8w1_8kLVqapAv2JM3ck4b-eLmPQsUkqQ-zkpwmA7izmCpXVuQvMUh5718GMytqmW9jrlW_Ag90L7to9MHrjGTm7aHLJ
LUCJ5RDolVF8gW2h_FxSkdl92jZb-do5MzirArWSOCNC8xF24G5AH5Pz5jt_1p6hW8-JU7y2AzSUWiWjN341tBJK7LRj5gjiDKcik2mGi1fzSfDpU_TKhOCI
L6WeSL3QuM3QMgs9Ph9Zf0jMDDFyz1xC5wm89BAYVIfa5H4MXSdpeCVSHW6hGWEhTMH5gTPIB4tKU2JXFOEF-RZNWPKAcPFlUrYnc1M7s3oyBjV8IjbdUnxA
D9Lkf1WSiWgk7Ns1bIuF9P9bfk-lKEhYp00otyKAdwrB4zzVeMiMqv3PAVO8MV5f75ZHaXyA94bzzRqeIlyiLcHdHmupdMouM_Ghla0JLlJEIkUSKdAooxVU
juVPYluiLaErRfg05RRtvSG25_ieZIQirC2AV4eBm49KvU8xJX6zh8he-rZ5MIEc5WPb11yYcy1QTrOaiy8ktJ0i3rOfAW8juCZi-w2XBYT_yXk_3zBh-o3D
PF6xdVnrJxkmgHlYRDPejdjSZkCx7f9rc1gFmn9rTzNEAcSFX6LK7yKDLIabMQEDDcvPfwW-YZkhsfhqrGxraKi2gaoIFbBndLMbcJvIlfnOBPe6VOJRSAfv
MQ80wgDl
}

sprite $tele2_s [128x128/16z] {
xTPNegCw381XDJTiMVjVxMavSKWl1EwT6NrlAUYd0_mjd7FEEUUSSyuvvvnpA5_eFqgN2Cb-L47O5XKpIv1iBy2Mijb9toh2keZ7hczsthU6i0hacAUgPXFi
aDgbljLtXu5ogVlOwAFQw6URo_0U936LPWfYmw5VxLhV49OR-_HAFzZrVbg_Z_r6t-19I1JugRxOhJx1u-AatRx4f_fg1n4ev6up37UHfAbf06YsavxfamsT
n-KmoAqmGwdQxSUhVJxVLhdRvrHszmyRdkpthbCM08YsLs2lNzd_926LLiV4L_ew9I52X5_JXGUEdlP991MrdINzStf-ggCTaAJ9XXNw5-vrmGv0pRRkDnlA
m_tujZxP0T_jTwrJoO7XvNxNzZqYNJZxEjxfCyBmMX_XHBQ31AVzhZNF-iEZVIG9AULIuOemZ-4O-fKDJ8JmPK5VxZtOvFJr8mWp8HABn0pmI3-_tcURqTFH
khIFT_fiS_907v68vKrziha2z_lMn_VB-zHjfi4ZVLlMlvutthZFntc12trShyzs9CAsVR4Z2TRfKn1XPYAycI-mKXyk2zVpz_jTwy9-j2CJFDmV-t59Fvtc
7-yF2_fbjnDLMskrrW8RzmaHvZRjxnuWB192Z36bb7CkfKnJhQsfTbtMHwIZFdq7ViQtfdq24Bkjt-uZ4J6pYD2yNvkg_Jhg7-UMzss8y_w8RzSFVstV-zwl
upbxerzj9rtj0zjSkTzN-6ivvvnppZddd7FEEUS-0G
}

sprite $rostelecom_l [300x77/16z] {
xD2r0SDG0CL0-_FRV-5KOLAWr8rmsvszR8ps6PnbLN2MLJZBAfnb5SlIJ72MLJZBAfnb5Swo2cTPXREimbbMyIohU9PLlsTPbNNAKajOblO4Pgc7PYc1MIgX
MQenYshXMLvHPlNmhDqhi_WLrxoY-kQLLV3AAdx5gxpYLLxnAgzubLT_hVBgqAuTxJYh0W4Spp20AEBxF-x9Ej8_4lg5c9ohEbUDqc7u2LJThLI4E-wHKz3N
2ggn5P7zQmNLs8fOvKUje9gsEhByfXLKyrR7-hDMK8sjWjHm8HkM_gGLL6Eh7cPXOlsY5LJVhOXpPXNvEIkevgt2UOoNykBKgxhXrrMzkZbMiio5a7ik-tph
y81gRAMtOxgMuumzT9L8tTlAUZLUSn-nzXDtQvlRBB9tpVLpnkTYkPSFh_zhiTMopg-kOjcNSj3w2ikujrSdsh4G_a7rt4hpGPJODlFxGLZHsz57l8ei7Dgr
wvtW0ks3NlrfVJKu4svokgOsHQeuLug5YgKM5HvGZQqyQp0S1CMT4UzdTlVTIhhZuRlLC7VghA3YCr4Kg_l6wx5wG3MqMizZ0jK8AmvkNyTMzN1POapTz1bO
qMsASJ67fRDonNhaSu-5rU4P65OFg7ehAjsQeUGbnhM_nXRf77yTK3gxp9RW_1phJKYnGcHXb6J12i75seIJGh7ggAHEdxzAwiughTN6MB6Qf-gjV7CWSJKs
7gKveKs5oJ7-HTZlwjIdYwAiNLPXQ3edUQuJakMsOGLLEx-ZmOLwsR3Y5prYzO2gMktR5RbsaCynKnDzhKo8XJEhMOoibWQaKkGcetPMolIbaSFgHYNjscNp
4gmeis3rWCgi1b7-QalrKutqkKmRvPxHIFLMKh1XCZaONMV5mQR4-B7Iqo2xTXM7VWVnhTKkDCLgGFN8QjVF94ujGgr32XKIOokrLuZ4nZnB8wipTsh2ogY3
BPMAISSSfkhwuTvPILXrL0-is7haDhiPJwZVSbDM_XX5u8T9xbOoRB-H2IgRu2movkfMhLpTxQpcvB7gg1vOxMjmd0A4ocATO39b5OvHn4--qbcDPtg-BwB-
wlLBVAzMOYkw7dTZAyj7pBsJOVp_lvKDPtzWLVIxbRzRkTfRFYVOq2f5Ds-bWpEZDLYUhi6aNTXtJM5afNrWnIyEznTDnDiQb7ETxrTHVcYLOepkkHNLnxun
UxkVtzlJiA6Ch6GqPr7FeVwsiJljLmFq4bPgUPFLX5LB1TPJgyIOsniiL-jOcpJorOgnZplVEYlRyFrNg_fS8HoZTTqU0bOdtbgN8bPGMRZ7LjIHkZ8oQZm3
xtiOMx79rP2aRCESmSf8m0tXPiKzCVNpuaNo_NgAzLBMQ-5Y1HLOpwsa69PSDHUkeIijbcOUXR3gxyegrM4t-KvqvmHMLxUf0SsXjQflkHSc_v6LIkpBM0cl
Ax22Yd3FhVW9MxngpDpey6or1LMVAAMpibWjYVjpy9l9yKx2zLPraNdXAJHXHSROlcPOWsfOoOcLqLfohA0Yt5ChBXh13v1iWtSoGok6KxPymBfYVxUYsxoL
JwzOqNkeHmcEO-MuxS0Agaaih2QnYh8n3Dxr3Qn6R-CsmKe7Lh8EUiMAtfc67HLMJ4FVMK55k6TMR5B4IgxkpUt66QpevJOBams0JQUtOjcm6M5b6GlpJVVk
MRQtyXI45LIpMAxynTYAr_xN4kgQwLQ6_osYPqwvjVNvewhiOdkWnRqGjzRSUvIQuwz5ldMI7NyawV_qaQsA-Z6I8uIEQXAB1vjl8Sx7j0IL0QJ6POdUpUGy
ipHjdLFtho_9bLk-D14BibibuzPyEWy6evh0UYCOrGJM6y6efh1UgnZdiDxGDKvYlI5hdCLw8opJM6_uE8trXYWnZ9V8uZy
}

sprite $beeline_s [128x128/16z] {
xPk7OgMy3eIHN2dclF_RNWJE_CR7MWCvoMqxs-kdqGX3R3Byz-cl_egOZHKPm_JRQ6ET3y5l2Zw4u2pJxx7TpZtBcryf0F1tMVfnwm8ls56-GC7yWdMW6tBq
azwj3Xzp0_WNw2VkIJ6s-FIHtE4Tw8OYjs34tmxUPNgBFMMf_84jVQ_r2dsg5QW98dRcM-RzEtrgoH6H4j_Z5aZomB-nvtyqpPCHVWj4BdZ-Jk-RrkTACTid
KTK0MPyVu5sDLz2YoT8W_hFE8SgzoZwT-xhrG2xpiYpR3w8vS0RJbqeZjsuGADh3V0477PAVJkOCFV_2Hhb5EhhhliPNQ57QlyuEU8AA0OXt2s0Fl4vFkuGl
tOUGmqO6FuWStNPVuqjsngSbCZNvkIF2Z_76352D1nrmQ4rfD3Kzmy4VCz_RE_ZQ_0c-YbwlTKsJfHQ_AC2EkG1_gG0Bzs_uLDBJIxu7Ngb0_CZjALTWBYww
m9Vc0HVlczQNk4UpDGNfuy7lByNSmU_aWxw-rh6F7pXEHG6EUk7x2e_a4Vls9RrUAIN1TpIGoGy8c_epQ31x3Vo6XcJqeg4BV3SL1NGIu3OUti7UEh04leBd
SKO1tGGicg_ZXI_k7MV2dsNdUHO-2l3SiOyBVnO13xWenJnvGwS2ZlEcKm9Ejz_eFjmVy6pUCrsJdPQ3F_KRGEvF-AE09D57MuMiAoxBN1TWD7wHFl0OV8pz
x9a6wVi_qkqlcwe4r0banJwQBzrVWdr_ncfEmI1hpvBU6-0Llb7mXViqEIQXTVWv5RSa502-EW0CVkK-JzsQHiTVrfiUtgwzj6bvAu3fZ_ngzWxsAzD5RJQw
yFK3nvHGm950vclp1_ix7lRJre0b7lG3SedlqxeAlqv0vTio_S9zIbEmlASEyve8SijUEng0LL2_05t3VXBh1YFT4zoRCUtBLJq1yD_kWF2HVbhc2N1ntfMK
kFDvpCyAAA375n7RC0f_WszexwJjT8Sl-66VFO4t-2FuIllOMEkSjOR1rlZw_n7c5rQjCW3mDQaFahVuVjdWu9ylmT5J9y4ChgeORk75VkQlrINeI4LdJFFs
TX4k-3bxR_FDbHcgTTc-uDSL_FS9Z9tuc_pXid_sIUXGjGH8_DHhuF3SFOSvZnvK1M2f6-0plBJDnEC3irC5fm3G_i_p1Py4BWtG-BvdNsYFmYUoKmBv703u
exd3Xov5lm--ma-Px-bd-4GcB1jeesdyHVYMXe_pypP3Gl8r7lmvy8_uprSzs1f_CZJq6t1tzIEPUx2L_9FmGyy9tUDZyE1TyG_xMdxW3pVvn7R4s6lyDIrf
cHVN_e_u6_x9-3af-FeE6Fcqb13uz91FnEwWT_coJMofu1S_ArCXHShfIgpOMW5Y7oll6zyeU9LFEVX5s3t-vbxoZmpxDT-HWbVvjD6ZjFxLroeLfCaGc5Ng
Z0FiWzJcmthsdZAzNuBWPrl_HwRW5mKepy3LrCKPsw1T9OdVrm_HP4-d7KnVVAK1M1dOuEcwAon_0PVUbnbofuqNwG2fT3oMad4I-rNw_XUBCu9Y0DaEaFSX
1WjEo_V-syQ6vM23VwK6d170lBJV390Bcw8tsIgrnCR7QP6XkmLV4pPgXGyaEHuWatUUlEKccetrn-rT7Jgz_sa2lk0RN_0vOEihECDyGZiVntb9uDwrFzeo
UDZtTDxvmxxhF4ynU568KxhjkQXIebf6KmsnYFYy3UlWlpngIobz-NrKmUPUiY-UQS1tmRxj-uDVxdrXs9zeJP4FCiOQAnxNEz_OVCFspofw0aVuWS_R24Y_
sWGbNmU0NVVxmkZFde4_3Q09kVsG1HyD-4u1ISAVNU5Uy5ZTFVPWgm0Q4_14GbzmEWK-vPNVOWzQ3G2xlq_Tfs3UDv7mHaHmpMFFzlxh4_-JPsKFHwoY_Me0
AE097oSaZU4dikr3C1Tm2LO5N1_uutlCVS77pOyCpe4x3QZE7th2RX_CGyLp1-qOJygvUsoCuEK2Tli9oPybz8p7nQyr00LaVbgluMLMWb6Fn8JlOcLVlGJG
WUijMETe0Qkc_slsedu6JQvemDq8nFpeM7ro1Hxssmd4EW4Ke0zTagUSDEg7eddrDQ7p4eJHpf-n42arf0NUTVicd__ISAS0HA0La5AQ8-WAdaZSTr_186uM
W0gQkI_1WgvLSBYFkFPKiNkVGHGWAi2YpRe1fK7ETBBzrm-meQ4K85hpaTp-NLfJPLrv1qlmE7plYgnK8Fny5I03aM15QSQ72vtE3yGkuw-z9qtI0-NrfpL9
7OiSop4ORVG0l1_Ljr_qNIqVChzw_MiPWxE0TpGSbxqMlYxQnCRjGKnPOmpUDOxbL3OcBzi7_auHRB8Ov9v0pxt7xDrNOw26FXeViflGVVcih_m_tbAUUz21
VoBuokQQkFhA9xBXCtYem0mQFxD9aZ_myKFuyplEhNjSCVMov0XUuCheFOr12m5i8hQXC1ySy9yiGLJpATFZ647tbeQF2P1tOMiq21p98_gFIOF3UsaUlV-u
X9ezV-Lk7E0_zAbHj8CpNOHnX7NWFsEUg5-Im7qKzW-O9oRIwY8CF1Go_8Ej9sEOteeuqCQwOju_JaS5pjbwPtH3UnY7TQ6xZzBnHBJBkVnfU8AMx_9F0FUM
XnyHYM4VL0dRMQQV_Wn80JNfrZ3zqYUVxY50pWdwnzZwiw68w1dvh_xgNm
}

sprite $motiv_s [128x128/16z] {
r9VNsgCm34HnnKtI-p_jzbt-q9JruF1nRbEEew1Xc0RZavdkf0dTUO8aFw3vBhrZ-GN5U_nL_jB23Vee2zpyf_MMv2jStS0zgzkVLsG5bq4dS9MbROx4ie6B
7M0llqohBJCaUt2--0Jsf_qd_Fh5MGxWAmF9v6NATRlwMouD99DUBF4bU4-uA91cMdthCjXPpY7S7adMbEaFbkKKXkCmDDd2VbdzKye8-_8F1EtdMp3iM0v8
o-gVCADXTmYxazLV5XMWiFRTNfk-G_nLdMsJSnBQQKvXRVhDe9qEWdsVrluBtIO8fJFioAvkx7sGwOsRkYesVSIUk5bbjY7ffG9XjumkilJ1jhVT_2Jh8N1j
yDhC-wjZMNfetTrg_Vbv-EgRn6Vpwmc1_1_scSwl7yyZLp-IkZzAp2ETAv2I7rqXG673xa1yUs-8WGLbEn4zMueImwZVqBj_ewK1VdskP9GGmFnwk2RbdQZV
ljqV7G_mwtEjLtMnqDjnbIu6-9MvAZ4C-fMvgY60-_MvAbqCzAjpLReOxjVdgdSntA_7i5TY6FFhSsshTo9-C8PBlp-tG-ZzBj-w_LLqz1WsXFh1Ecq9zAEF
4xRTu1V_PLyBVzvVLvqTyUEFioOHviUVPsDb_gI_RdFRfzA8Vo8Q3FjvsiVOjvXWlviGS7-uro_nkVxdpn-__fwqVtZ-y9fdvYz-_td-_HVl7y_lNtZ_lBz_
V-_UFcm02c4WXlvAstzWHZZLF0cc86SRt1_W_WBt9xY_rVwWznUyFzdzRUhz4U-lU7y-SNzVW3y0_kBva-TlcZy6kmpmLyUVFN_t_e7tBxn_ulqRxnzv_yhx
Pzw_y_wXzo-zV-hzM-yVU__Q--VUly_zmL_J7-J-8dxYTN-Y-nlR7-7-olPdjh_3_M7XkqD_AVjJtz_w_jZtrxu_r_tz1W
}

sprite $motiv_l [300x56/16z] {
xPi7rkCi30051ficwVwd_KisRo6AbOzOyLRFgsa6Xj05J16BWpaka6c36IuICpD6KBa85MuuuXjrWLqkV6LEy3-5xr1syCI5oyJCv05WuGv545oio3Sg03GU
2F30HMY3cvK7AZnmKRY33hb37ax6nLHQGsmrhmv-VJ8FD1v8eBBbZWELb3iWSLiZ7i0awYRcBqbFoSXCBxcpmZVs7xL53ozO5m10tWT1fur-TLNS8VSyd4Ye
Bie_NeFWVqY-qt7utASuri0Iz8wg_I-CzradNN66VIBhhXBn7bJSPrqrLbnfL0_F-5jMOd-UeC6KAzsg9zMLRwn1yPEkAckk9Z8WAnO18F0EjCovqh_RM7CL
Y7KeVSvLPjNLlAmL-KvICbLWofNUjHNMN4NYb-HFkTfusfNQ19RsE35mn4_WDygKAwuWsPGCT5KwwJEk8Xrm9JlWAFz0YJNQd2lUv51DcYjF_2MhmPMQXNbN
f7Pv0G3Gweg27AerLuqd57YxAuzyr1K7EKIDEgBL5QCJbQ6uIZn3DRjooCTT9HZ8ilrKaolvpSIQAqVoPoc6k5NvTh2wgZpd2lsDKDKPeoDHZ8KChcG2aJHN
qYA6OVzCffkfmmFKGSrLuLbNS0SrLx39KcQpAuwzXQkkK1i-fSK5G1-DEeghn6-xggAbvV8TabrfCxiYtpzKN0NruRAsiiNLoc-xSYGg2bb_Y4UJgvvkOTrL
5cxrXpQ3gq1lk0etLfJbm5TZj6jMLrpqEYMdhBaL8NJSbIUUTgKFW_Xwa5mRsLpn1WkzSaLgbwHyUi2LGxQvGb1SYKvsYO-4zrnHH7xbIltdF8_pyQYhnaPN
N5-wGfX3kfg7dDAhQiljzQ2hmcPNtDpVu4gI3xdYUd8Rr3c_3MgaSCmLhoVrxQZfeP_Gjujn-QWhF6dEe4rd8lw4EODmywKhQdU4ct3ENDH7uXqou4-OYmwW
ct25oYesdxF6yP3sVua_OOtJGGyphfIXfPspTlO0TRTIyIUidSM1oRGhcGCqxidehXpkxPEYPK_6w8eYlEkgYlVFsElpS7SjdWbesEkpkjfWqfM_inHHy5Fs
aFtOgCTSeM4FsUWgmvGhdNBEsOH_ZhU16sWucx2vgc1rjPvpvjMt-4HHqN3cPNBLmEgAt3bdgNwKC1OL3MUf5bVepAxIIMVqNXGemnqqdD4RND42LbTeYFsO
SWL9D00y6FjXSqK1hAvauPqzfaYwWlhO0F1OJ97HrGPMLxWOOjLcNJbyg5Ky5AjcT9N1w8gACyH0Jhk2G1jqy4WCfD5L1PihpFx4sDeyMWZAjoPZQpLy7eWl
GdYJyaCPMwk6r_wcCTlNNO3hZibrTqaR2gyxSVcNk1DttRMyxl1U85E2AIvYSN3nBm
}

sprite $beeline_l [300x63/16z] {
xTk7agiw30PWIt87Y_T_svirQ0YE17l9QREJ__GIoeTSmApx9Va40DnbFW7oCSOKeyTVWexaOmu_4YgcFVWkKigrBL-9xgS5GteaPqc0czlniKoDbptfnqa9
LDcITgllgu6ll8p9xcyczWll992_GkvsmCUK1AgkURP2zwr0c1Oba_kR2SiZCxWjj3p2wEu6LwdLIUBX6G7STJ3pebg1-ukXVb0HN0zMeRiNwbIRrBIb8ZnD
7dp4wyrC2fKSsTyBT9sbU7mal3dQ-Ase16hk2HrAk30bSkV1MM7Y1z-KmFtD1ERjM5YE2kzJYPGujTOoh16hV8K5bKUdce97_4jGzf7TBolQg4IgzLG4aGBe
LlbYnXMVaQ8dGVe7GiUAvt9tDhHJRL3yo4GWMNijB3cdU8A5ovOMwLz0idjIpk1k1UAHghTfeNeAbOu5pahU3YI2-mS3SHQfoOExbv2IK7MfjGaHZ0crOtbd
1DTFpkJ-qG25L7Bqzti6UgLYpWXZiDPQphgisAqQkP-Rc7BUgVgmsWAynazJhIU51UjyFRYV6-oTLQUIzfS9mFLlpodp0wiKiyT2_dlpSq3otXFzvd6Nf0Ns
gdga1WJP9Um9RPR2GgV57yiAa4W_U4mzVkmrUyBH80rHFufnOkcr8xsUO0-g6wRnBzI30jcHjC3UL_4K48JgcOkc9bY6LLg-Wkj6GsrRJnz9BK1HbI1hKqIO
5oq7AqYyF8KpAjTG3apYjy_Gq8DKTS8e7f1A4QfMl4WDLfYPspolXOLsTpL3lyvjsTCoNLj1lc6btu5oeqihgBUi7AQrhEOSIA2EM0uWyiBSrXxBi6hocCeF
9yWSuSHAJaYrcgwii2qlQNHY9GQth1oGVuGGUZG627qc8OMbMg6SQk1b36SujuBfXfNz7oOujqA-Q-LWZrEjV5kjriBAu9JGTXQUcL-i14kpagdPdJOe7nmJ
pgtoSjlgUNQWIC7MgCGgWZaCiiUsg8c6bJGamwgTMya7cMjEgSmYL-7CoY_thM2tigjgRuHaFwRbkFNHFDVol3h1J2TMQJcrAbuIZrRItbjO9O2gF9mwiOBA
xrYTbLNOpbYi2fuyZ-djRuwqRWbmV_XUmRGYDgtu-7Tqj88wzkMuOVaJgx3ShoiuiyAuKKaZh07CwLLF2t2abePZMK6zQuLDjZIwHziAs--nwlEgvMY5kbMM
COZSCTA4Ysub3QdTiABMWw-ZGRAjqZfE_MehwTMVhIAuCwiPbPwifw5c9TTv3hPLiApWAmZAAaGshAJmIlZVLjjFkXLWQiFGFyyLpwsyEgFlyRfLsWRGxrYX
RCa8-C9dLcB9H3UipBe23384FzUL1_cWOYK3a5vOIRMYjZx-1iqAlsybzz0NLc7RYs4r4JudFLcXDGu2-BeZxLRI0l-FbU0KpGfw8J0vtKfehgs0v9RIjf95
kOQQbH6n2h2Uzs05KikZLK40GJwrqcQKCoXMGKhkFIjP83staWOVt0qh7s2mWaSmL4LgMPTsNET5QywWMCdOr4QhlMF7KokwiiB4SenvigsaOwzmnufIm8rA
WZwrHSzCdLEtYdPTkScqakjiM95XfKhnCWM4V685HRPtmmfJpW5t9mg97rcqC7kGcsi2emFd_rTNSfqjAp_KAhrQGLYs_hpqbQmpgo3_TiSA-XfEJk6HAFUU
XbJpKbKEWZj4s_brVoNNcRsph8BuctKb3mcRBF9cUowAaspkZfMBQLYOC3FvVRMUl3dO1NiSh2__qxDSPyCgIZrQLb1ubxgoYh87suhp8VEpbTyMl6HXmaob
VQI4Y6Rn56UMN1wjO1t0oRRAKe-MLUBru9oxjY9v3dXYLS6-ny4aXNMAnHbNfqv52HIHShYJKVOOHYkvpeQLdC04Pdz5BCFejTNUu6qhUzukAwcNZR35VKRn
vHkSFJkFLjVED5YHp1TCAsnIgePLbejmRKMUvMdsNIjAILQThSBYGh16NXN1azSP6Xg8CnojSf4JDQsy_9NH1c5-dTCLmofDSi5kMy5QM6OhP9uZWiI10v_Y
sNk6Im5t2BNjO0-eaWedLaLa32laxrl9GRnXvIX9ZwLXCIU2FRspqijgNvyyzcOuiJJ1Om7AmPfMia6wilB35REj6hvZ9KEXZiMPOA3AIcyrJ54AAK_0ibFg
YfFJhG3s9H4yiHe7BuZM_Q3S8Bnb1U60zQJLfAOadIgXC-Bt9IwFwutb9DjZqgmQ6bQnRqRwETjABiusgdjPX6waMLLuqye1oUiVeiLz5IaWZA6JTzLa6gw6
ezEiWhEiXYx6N9kGb1JpjEp2BNeqLhZkMKd09y7wqchSIY0OuXpuB2rG3zf3AMXM4rnRCUbMCXKTCeT5ueTgNx9xoqe2w6FkMhMaG0YlSH3aTL4pr7IgggwG
itTNLk9fpqMFOG-pORKmlcqb0S2lW1u7cEGrv5CirgeAdMQLuTHAF0shSHLMneh0hDTLTFUjb803ApuBrMcmADCES9eLaxkqukGigx774dsekjK4RrdfN0Sl
j_x0Q5ETVvqN5nevMLYkhKPcKL2_LeeZoELIhBpxrLPTgdl9R_lO_oKbVTLLmETvct-sgdnL0EOrHtZ8FPjLc7dXLaZ_wA6VetLlF2VQ3w2s9jC6oZr7TVdR
tIglSOU4_9K2pWxiSLsgKtdud--w-ZVUTGL4XE_lZOPThSV-XmBo_Wp5BZMqlqzWl3OOqYP5yE5HAdyDae-vGvbI7wqG7qbxv6RX4wDZ3h4d-EzKr2VmcvK-
-UIJ_m
}

sprite $rostelecom_s [128x128/16z] {
nTB9WMCn3CJGWhTlklBFTuwwMREfeGGUH39_zo3cupCktuxBj-FoxQ3oxQ3oxRXyEoxVZiktu_Bjk7mxBj-EoxVZyksuV3iktuxBj--Z_BJR09TlHnh-2d3v
zktoxTlP_NhZykq8mp-nWiMR0TEQ0Q_M3BYtQi1K3NYqQi1K3Q1L0vvr0wPkmATkGEi6L0we6q3T0Ee6K3U0kW7qG83Zz-xwzwZ-8mVyqtnm-U3omUM3omUN
3ouVN3wuV73vuFB1vOFB1vSFBXzSFhXySFdWyi7bWyi7bmyk7rm-k7nm-U3omUM3omUN3ouVN3wuV73vuFB1vOFB1vSFBXzSFhXySFdWyi7bWyk73I_wW-hF
zKBqvxgkb-0l_aS2-CPVvrV0L_vy05_vyojWmvyEOCEV3c33dxu1Dlpf03RywHMmuKy7iE5F1x3XJzy06_vq01l-z0hOyAS3wEAD03RywHkWYpScmEAL01Ql
1B3XJzy0RQ_B2s1ztrb1-xxCWC_obO3dyfqR-7mkDU2s1k2iu3QN6v3dMmx8xVuNx_O7m2y
}

sprite $mts_l [300x300/16z] {
x9g5TlDG3CPkcEFtVzgVSL_Sw_5MImVRi8x2iVi40000000000000000e6-lsIrE5vx7ypdRbyGUHLkkwIpCLXnUnLLvIHxfwlaRsgPtrSUpokuglgKThg9X
xQNWgXmMeSVLDuPmLhWgHpWhN8rMvIYu-ibfDGPS_MAgPuMhQ5WZhg9X7UNDNLbta_AGcsFtptOL3skikNfpdl48uDckvl3-WAjYDvXm9M75ii9LOouphXwm
-5cbTpL9MD6ivdIk99Srk5hpaiwLpR6m5XajeQjWM8qSrnAwah3QM5OPNUa2jq1MQr9NIpsiLRBAwKgZsQgJhMbTBRKbRb9ULbSQrbwPQalhIWz7VIshhAxg
ONMILL9NzR1soIgpA_t_g6ILsTNclx3VPNtIkgg6rOkIxAusxuNz8OUoxAxqg7Gwh-LtN4bOavSLhhomXelZ6Avs3Kkp6WnNt-almXeliyBLhkzLJyaALzTX
wMlv0rVEfTHywaKNhgwlfHevMk7A3KkomfM4vN3YAXhMPBZwbp6S5QxEy6TikBB9pmfNqR1cmrKqBFiChletTEM7jNmALyFRkhBP--OMLyBfPOKhPVQomfLI
XDLnXQl5omfNIkDaXIjbd_zZCG5N7jbSuGfNkC8Lhd25g-CXzcJEPypg0sxEL_RWG0000000oF-r4LHLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LMddBX0bXq4m01Et0lS_xRgEbSciFlxl1gNnG7u1uJLxApcd3t8kjVMvMFGd8AjdkYUroVe972tIgJpHmBW7CafJFUD2pmX3lP92pmfJNHgq8ulwKsZJeSv8
f6rJNU50DWYM17h9KZyYlOWnh9ibTMBINI6LrZ-h9GMwQwWBGhUbSOXUu5K3tIH-Us2SedSSXMxewW3JjR3q4Kvq9JXjLbNFL9Vh1Z5q9rEmYhvvdIxrpIMP
msLeLfF3tnwQjoV_x6w9DRRd_cMO4TwMlBsc54FdVLjU-E1MVzQy3LTJmJhei89rTQLWNNv7lGUo-SmEedbJ1tzrFObO8LOWbbW1OeLO8LOOsn4hn0h2RuWL
zeDGp6SoqCndVJ3DrpXms3CuW2uqDUDBtYR2e6RkSaRRTYTaTqb5QxjrT7zPaDj54C7Vj50sy_gxmqpaHPU2RAMgHPVr9O5tQfswqwg9eOyjhoKvWQx5zMnL
T5OF5jqIsg6toCoUgrCptP7Q-FRGXp2lsKkWsp8gBStOMtRVle7d1goAEj9GbMhNQLyIzMNIhgpkSAGj7PSwHl70aqvurEaKLxABGvsRcIm-xnTXjKYFX39O
lm6UlIIwb4gRX-Wj8CB79ymY-iy3000000000000001u3m
}

sprite $yota_s [128x128/16z] {
xTi7SkOi30PW2KH7klzj_vBkNU49-kIK6J_Jj-Gr7Mm2Frs85C4aKWpm8EgJUVQ4i0dpOERP21xHM9vmHzWI1yiJhc1NvStU0uGXRmfOPVcWmeOcxvZ01eTy
C3SgW5W-660JMJxWR6Yt9npCrMziW2u7qThx3lhloH-_FF_El_Fl_29YcyRH9pzRyyDqoKzoC8DjuH8svaSHCQtZ92xhNs0vo8QEe-mSpCtOZClV0ADXAqTa
vRajcXnmCemRfTqC0s1d3unJZX2iMAc0xU9FCEjoDD1G_09c9FjDMKLiiuzUbjqvAB5eeyy-0lOcuSXAbTa5bgqk4AVomAuL82F04aqHlzwdrwVC10kPHIk-
SmK8rm2Aq5WyYw-tw9DH4Fw0HVs70HvLM1IZHFmG7kiK1ITu67PHyMWb8Y1IQOD5rS11dBB2JsHb87X8B2OSmKUnnIVmKcpnVkf-V05FbJVZC_WgB1jc1czf
RiGJ-8jTFga5k09-hWrc0cVw4gVZYd2XEFWqlGUu6BMv2fyrmXV0t2V_7TuJV9b0NGuQ8NofQjXb_zhyE__El_Fl_3l_ph_px_oGwfI3MId05qc3MTlzTeBh
XJfbQHQ4Is5bmxdR2sR-pkCV3VcK7gy-_NxzsmV0fiH_tI4uTDd13S4J3jdK4Vo48TiwUfRUeBl5Tp5ft_7oqtykN4vwp7FqFYOl_m5Tz_gVHoM49qXri6X6
W8SrKVpvfWb9NnQhzyU7zGUms5Xj0V-XDmXKQVWFmimRKslexXKmjfeKctC5qEcaWf5IeeZmhlj-X1hhU4nzylCiq0ZN_QLvVdwVg7OsVj_wHkM_c6MbD-cx
4QwhIpD2VjNVJjRZZeikKDsgd-FPUjpLozyY35PbKVmkghhuw-WqzJETBuXC-fHTdURUWSgb7AK5mlIPWe9UZY8hJ6gz3NJ9vtIe5KrJX-qCBfClHsM2KPE8
NUvV9hKQawmnQHs0NU__5ZcXvejhVfKJMUaYllUlp_CBFFcs_7nzVfOrfklpYMM9u_NvOShImElpePrsl-lpYTVJtrVaGvU5UkdlFpJjHAglS_sAtp-esfbG
F-eqb_a_yEeaLVZylbVssO7tvIuYy-BAaJP6cyVbLqxwFHZztajXbmD8ukLrDipZ_Iz7MjzNcmHsz1p2Csj_MSV_UjKIodnvD897O6fzj1n0XHW2WYwKrdjB
26ktsxy
}

sprite $tele2_l [300x118/16z] {
xTm7bkew381XI-v5slzo7y7pSbkC3GaGZFxJRvtv3YXAOTJ794cI907W9G1GpQGhJaYvy2KgENgB_u99Q49swbBYtwCSpEzS4jX8pEp_jLeg3bLDqc61Qbin
KrYq91svrh2gaHCf3Cmzgrf4zTM18nwrucBK5uUHUToAoNx7uhILAJniLPiQ2xHn8PMYDhB4zrhHZ5Y0LoJwuI1G_-IOxxPYqXCYyLh3ol4ZLbnm7YJ-gMTb
-J4h3X-Dj3XWAbmRizBqg1MRZpH2RNrCrxL7CzzZXPaVjihmKKfeh8-vSEq1gy0zgyzV7AuZAHVYsgDMblTO5L2VKE7QFYie7Qif9XOTOkLvdrNw7YkadLQ4
NsFbUASLss-n0jfj5TIR-bcJy5LMbdTRvJSWrGs0b-XbLgbZPLr8TAAj0QnFfH3NNcg58rTSm6Q-bNx9AmdKakRQ6wmSrphtQi2_omgqSJuICx_TAerUJNSl
taQX8XMkdS0AY3UZVx_z-AgbOK4AAz9vhCpuTu_qP2j0RHskH-RJMJdUBAgD8hSoXwn9XPZfP5P4kJUkjDh8FSFgUZM9k7OMAwAIetT68tGlCMIrbJdkE0Xe
pE_pyXnMLFB_H30yWvpQIXzmyWpQsBe1fFDObPoYjmsYthUlxxCgSEy6S2OhQ10DlgtWllTWwjvFMf5EPpMUuwsAsinoez3S049QaJxUoezj3BN0ZUpc1i2r
QQpY7TUZ80yS1krl6y1NMFd7HxldseHMwOwL8VH7krZLiFJ6bLZrBtJXDrlvkrvMMRt6Af_IAgZQ689zhbMEtjbw5dikgno3TrOF7WHh-0GhefB2IbHxlnLT
loplRfywGkPMKHrjXHj49x3IRQ1H0dsqLUraLkEPphSycHK0gaVJnCtCtLPq7Of6dyiA050Rwto8USVZB9YvMO9XgvB2FzSSps05Yq_AXpnU3OdR6TMpAZ4q
3XmdiTB7FOeEaTj5rR2YbKYjJMy5uQwFJVZK8094ZPDRXNqFNjM16M8fH6pcjlAxFc2IYFYtvhRokvvzXC8yjTKuLLHhOkNuLWLVO0M0U7QhFXKRzImhmBf2
nvXoeNnsgpwLLy-oidy-3dfsgpvLWkTPSUrZh1mF3YknyjmRLc8rIEMLM0rI1ILMWrG9nEgdm6DpNQoWKlKln8WLHEvab5WDKbarkLKfEKKuWigfwQmkD35u
vwmn6X7Xakg7YJjvDPsLQiZifvhDwi5qvh4TLAnquKuHnEe-Ah4oD43r8gkSKpqqMMkqnXDPZLEzo4h1gPyfiWzHpN0Vv-uS3rA9bH-a4Yi8l1MLw-uVlFVE
LIgniWk6jTOOhJKsJeZ4QZInsXzSmaiQlzmALebBnXXhtINlGuWn_VKJ5VtyLgl5bS8k4ZviM3IQn0fg3OgeQf6xpM-bSywb43SYcCxgzrbXrr6n567e6l8K
LklxuvOLP2BUhinifUlBuZeqb-Wdk6d5_8rMbhTxkPLOYPLOYPLOYPLOYPLOYPLOYPLOYPLOYPLOYHN_rGDMl5YLZx4AQZFyC-Z_4LpyS3jLs_uDRDVuQ-jN
XBTJDS230lNs94dw3m
}

sprite $megafon_s [128x128/16z] {
nTk7ikGc40LGcWpTj___RnrcJTb2UkiHhN0hBgMg0o8iF4RkN8XywGBz9oZkay2g46w1oDqMyh6o080U-Ge0qfAdMtIV-eQU_L42z7nv5IWKdkW3VmJIKhYq
wMt6z_usu79L3KBkK3tXNrg3yU9F-1VMWFBG5tnLSFOMVkhtVP0dVmvwfbNTLu4QVLLfOOrF7QfsNy5vGQSYq4jyXLGwo_i6LRC_WXxFyP6X5_eAJcVu9D1B
VONax_aCwCM-0eM-7Nb3j_bplgo0hr23Rwq03VvwNv5Fl7o3RwX0XjxeAvA5j_igqJJlvo2TzC7XPpumz6PVqUWddZhqTbzHV_8BrEYR9a4IVSRdOEXykwze
Htw3sdnR3sJHvtoEC--xMdrJ3nGywQkaBHz5d_JdLOYgFkihigNvTb-xjpJVxYElDH_2BC3uLrprjT52yz5B98gbm-mZ3Z-8VXafj3cTMNojD6rwJitQB5PV
mbZwbkPCnQe_xzsWtuNzzeXezBNxSnl-x3RfCFe87rzE3jYHQlD71qGi-iNcZmweUANzemE8eL-caBd_zwitGNLj_8jQVMtaqgd3_hnVH33vJAUsdHAd3PFL
XtU2KzicsXpJpNvqq3D1YTxx41lq4hywFHdmNu7gDNudDSJkyxk-oii-tlR3otv-sIz6tnlz-hBVNlQxhWGO8QFFIpgN_2l9FUpFLndF-v0uuS_sFuhR9put
_eKE_8IdV8ZbqcGEwYL-WQu5PTdtSIHLw6AGblqY8u1X_LpscruGqBi-l-kZ4rxrgnEywIVNNlMzos_wJCw_wJTo9E_vYCvHWyMtxnwZsSSdEl9z4V_jUx7v
a5vohWoe_gSebNPSDEzag9byjEW-IOpnHFMV4Yh_5ZNlFicC-V2KOF2bk17VCMzF8--A0cEwWl6oxgFiRd2HtCWON9AFxfgGn-PfsGVJl0r2sztgeXzkbYHi
AhdWpnUvNdP_fGtOFHKmtN_ulknxjmb3nMr20fNjKvxdFoPcNEGtGDokIZnLgK_tNoxmlJvj_RQx0SvOzCFa7x__SF3-6qt7joM_x1gBj1z_PLSqFvQnui-7
iI1ZiatpZ-Qp4XhDFp-mhp-kOvwJKNPFHKoz_qd6ag_8jBqHL4ZSBRQ36qMeRax5agyO_zc4XkcMbfByKCH--GG_-mek8OJK13e2pdyNTUXn4Shg6NRsHw1J
eFZTgUF0fuO5Vo7WOFZrczsNx8wJv0aVrVsKWjlzkVFd8M3m3Pq_RU5kz3cwtyKpRlLbuazD0hiloVrVek0s7uCtLC3Wo-0D5J3uaWmVFvXzS7JV9Z0Cle4V
yGtN-kZ1yFMDrGSgkPD9ZAjyI7Rd4nfmYOyUtKgeCEm-f7gtcDXWzT6IwVE_3eiFBkHCyPcnweDhkERppmN_mYzGVMforaVFasu9nSButWVNwDsryR4All4X
V-5qq-VVNNxZ0m1F-BKXyZuENu71VYBSaYTo3wMmo2zNkBSSY9RiFm4
}

sprite $yota_l [300x95/16z] {
xPs9SeIw3aJ72zwb___RjwT2w95fudhSXUbQxZ8knfp8Sbk8v7LH7uLSSbmO-XovAgegpIyCVOgQ_bVTdQA2eGzJqY_Liw5PlrIUoQhhbuOx2IiO-Z0vqIz9
f8Vg8pEMtm68nD07i7eegm-h3wiFgm-h3wjjFZGydPNZMSMditeDPKyks_T8yGy_usYRZopwy3FEg-q8U9PgVtgTGNLZKtjz9giWv28i0FNHoLqYPox4FvHL
rMzrHmrhhzTd4MeX38DgkjS2-X2t68BxSxa6bNJcGtd7u2F18SwNSoXjoDVSHYkpIxf0o16J8NT2bUqjgg4x5UxfqFaJdzX5LOgpFgwYHqarS6KHPIGj62jd
GAoWNDUT93kyZEXEmnEe_WTNmWoLpBBarlMz-cROH4Bsd18H2812Z-1z5IN32gS-fZpjAuQkjdem7Z5n6cwopKjWlJl6UIXocAY_j5zamh29mnMbCycHhYWb
Uqw5tUJ3ECwbrnIyzrlfSlmeNZiCY2CCMu2iSARcu5gy48SJsZmcKPI8_JFXMMabWZd-f3XqAanoOPLLkd27XVyQHX5IwTImYJTGiR3SDLPbwfk6ezqx7_f4
shQB4kO8DvHJWtjb5I49gNAdNHuMt_IHphuxModGyRTTmNvmgiRDynMdAYjHnGSrBffsEHkWRzw4H-MisH2sWTgdmM3F5UVxGRMoLOHlxIN564BSIfU9KVAv
xpNsLzYhnacGymuoJiD_N2jQDQ11dDSXMOtiNtiUWzsKjok5IR1CH52uB4j1PLgUogxGhFFpbYj2t1J32cAPAQJWN51I3OD6sX09H8474iU8fmUoiiBAFajs
CXvobsF6o1OftZTmdsJYZBuHvI6IbMtw0xryKj_D9WMt_jH3qubVmCGXWRbkN6UL3Lj1AjD6dVSDH2QBGFTqpRHrLg8eyVUnmbiln0v9rlI368kGP8KZKVb6
LhQBYdPzNs054iVkLLQTh76ji-ApPZjrz97OYM1WeLXnGGe_W_jOOHQVdnGBV49iiNsHLTc7_Y3kcsErxXlc5OXEE-TwCf9dvMG_CE_1tSeANISwLCCnDFwo
dc35LN3ZZwHHRcM5sMbwyWb2RqCU4Wl1Ycd-QP1BxsA5f-GsESn5042jdBp2AXx2FX0fasArxXlodbosRqykL0OgmOfn7mAjUtUomkFm_j_7B7LSEEusWXKp
kG8xTxY15VUOSvlrM1BHohEYvYO1zyLRM17F6leiLle5Lds15Veqj2Dp-TZtvL2_22iIJGN4ke8ON6UrlGdpSA7avxOsZlMhvDRRTw6a_ITWjG-9wot4BW-Y
WhpW6o2yZNLr0ol3UIRIkYGaPRSQyIfCGVj-LkNjYSPHnuVGTQ8ULtq3tD_IFiYp8cRL38IEQW11ILvielzMF1aqxl1N6qo8FcjbqHD91SoaN2SQIAxuzhx8
2ZEx_G6giAqVwxv1FFjk5E-thxEA-slulJ8478UAXyNxXdA-NQR_VvsXwaxoG_Cba9LKNVSDulXWGH6dDegL4sM44RujzFLnyi2AJo2elbuNJNnVsxpfK4RB
MunRheFk5rrdLTcs7Y_hzVQkdCJD-v3Rvko6_EwMMH7Eeh1BCF-ELLHM2LUWRJf34seLygo8tKqSQMt3xrWrPTLjyoF5dRZKuPTP6UfSO1NhJdXMNfHMWCjE
NrwAJ2FFEgj4v4NYnJI2LVvbUsb_jy3yLbehAN2DFEkiS74DJzGEnNEiy1gyn4r_JE4heKkBL6FnEYlqXzrFZqje5NbMyPUlf1JSux90_c8QUTPPXTE-Fj_1
m52iR7zMorkDTsPlG1DqUNUkySGcnR9Yk-ob-7ajfBruLdGbmIxv1V1rK72eS1lR6Yk-7r5gTD1lY8wLPuL5FggwXVpI7juXtFZVpy2peZOewItdb7FhGXJj
2LPG-QJxI-gHSJFicCEY_JehL5TQtN6is2AVlL0BpAtlXs0ABOHhM6VbniAxk1ohpjt8VXYazcAUlmjRY-DPSNiXyJREPLO1x03vzD0T2snLtwWTpViwArjH
I5GiAoApCmqc-7lLcdb-33UmWiYYKV6iwY_Q8_kHLJHP3VSzT9dLE1_SzKGZdl6cuYeoSxPPLIEkE5PCfYpKQq6BPNytJ3COwItgEsuIi39Fu7MTLRosBuIs
-7PUilrDPorra6-emChAh6cTrIiJYGPBZAX1rXgBQSByO9yDRx9p9yZATGKDRxFY5Rk8yTjSw5VEfCPBtzVJ-oK-H7haVc0YrR-GrJTBA4e0gviKScrzY8YC
LZFnjVV-_lPgd2KSi7gQ-i6OuIeS-F-_BDBdxqsuzhuycM7eGmHWXZ_qhC5Z7TTXw3F_FauFF_vdQkDVQZ-pgMymz6cAfPRD0KFd7J7q5dtqqKSV_HC
}

sprite $mts_s [128x128/16z] {
xTHdWXiX38RXZyuOaEv_ssJaYecpNTlq_7HxAVBmfpF66BfuwPihUWAl21UDxpLS43yjumdqtxxdUr6plnv0Xsu_y2mgzz6NxUls8zzAB-rl-GQEOhvAJ_Jd
0nXO-Y_XbrzShFt8Lqcr7o3w_VQzq-btY7G_J0Ulq-S4CURjHzRg3uZCHmMYg_Nd0o28n6hzom5CsrViSuOOq_OL-mEYC7E56AfzBkSKkSlsDVi3el86CPJx
N226mowpTfyW7CHGxtF1LMRzFZbSa79VL9mLrkxF1q3gVL6dxUltoRkT9-t-1GdMxY--LdzyK9zxs_Kdtc_yX1VyxiiPOumnnXXZZ37666ECCSPGhpbwzvSF
gHm6gsh9OUOBiPOHyI-LTJGy44arlueQXuyB7rBE-nHgNa74aTi6dr1FE27-O1r7QIvjMWUG7jnqLfe01p4UZ8NJcRx0YtR47-i0KVYJL8YDFqc1EF0doH3M
_wNtltto_3U8pCgUVipc8_vW7gBndGxXbGRG3Pu5YAHq0V2TRr22rX-Zu2HkWtWtMd5GENxXSULsk6eA_U7nI6KD8-ZcLzLX5JgheKDokELpPrqqMYqvfLpg
eHD_7SOOymS
}

sprite $sbermobile_s [128x128/16z] {
rPhPWjme301L0f-0_Vz_kpqv9fwMhG6RlUfrDoaiQ269I1i8065QotwWh5D000Jvsm2GkEwNh17WRzDhC6xB4g2_6j2qLxA2qDUkyzx42FJpXxmtioey5ei8
QDblaG8FzI0QZBrj1JnRmBe_OduI0tJQ7nEvAOUmxHt82hVyOuEaUmZGl7TZeTLEs7koAMtwOU_B0Yt-ccnRqZmEBwObRHKt0WtwvVixpjG4thqSc-n-padn
we95Xt8QgARDXtGjpm4taX3DNipGAUFE020EyBx-eDA0ev-HIWv_Hm5fWVdIJht_CtbDI1l3kRqe3Nu1uluYQgC_dEj7QOSvgrYyWW3s1xyVAq8i6Xn_Tb9d
7xHSNqPCP_gXcnw8JZP4p_JXiTx-jXMnm7QkfvTTVmiIjT4F8BtyWryGwPbUEe5ypQlMJx9wXLx-y4qk9rXzf9VVfbLu2qyn-gcFtLwfzWX2jFy7q2tsbe0S
OFlxDd_SpqZuzqwKBXoc5au0xEwlYClpDcAGFs2ZBprWkjHFUFNso7CtNWkdRkhRwE6Fb_O49ZCVYJotCxknF_9--agFho-N-lSAYFwVxvpxP8wssQUdUY_s
0yxDTrsq0zKZEsTWjmMitto-LH4MHUeWjam1h3-V-MFjgK0NB_Q8ORIdZzFYAL7XrysBFHL5ltnYpkZWNuh0s3o3ekh77mzze1FxjNK6P_sJE7wt2uTBUmbG
sNBgXT_lI71dPhDU33WHcMpoyVtxebYzzpmIbOi1Pn3Ujcnp_3Q9sJ1Q2bncwCcKFaag_7jMQcV5CzRDxyeamMQFd--t5GhagdDlo_qDgMkvubaw-Vwoomfu
LQ7nu_bjHl6Bl571cN4r-YqHlDW7ERE7ilVoxoa4jyYpXFXLnmE_omXomhBxVkdarxfiBvN-eSsUeDB_jl_RSx_VlZX-R_zP6_JUYD7eRFoRAchBYhh-E-SV
1EOg_Q12_O0PSVnc1ULR-mQqDCJ8LjzueyEpXqP8nbyknmBjvp3odNyprKPw-uA6pgvvJWysJyos_l1XRdeVyejTarbAJNDxUr8TRARGzkONnfjl99CPyfcG
3Csly_uRepjcn4u_reQdZCf72h_LNim1g03-DBePSVJUBRuezceBI2MwDJxEfRFYcFllh3gPvRgS3thA-r6kzWjAWpwS--T7esVkZ-GMJZFgAjtmCxUUJB-t
5uhq1pjbvYsXRxzOaBy1BcVyOJlONnH5aCxOpzVZ26exK7e5m7_T_PGm7kKV1A6tVxsUWaCvsb-i_Es7Vp_kyVpcBmDzzVWFO5gEyXTPwQgVZPzZwcB-a1zN
i8ZGJs-Zd-KBMZxyvS28T0EdHpi6u4WEzBAJxUTZnj3bZQH25xtEkm7C6BwyizB5hqFTK70znBwyo7a1v2d4tSA9FtxHvnVb-G8WrWxZcN_hFocByimUXjsI
kMXEN-w3_LS47ld7-la8XFnJN_xuywfF_4jJbyoOlr1oAJb5eDVltk-mOVcCm6454ptVO3TrvnF70r1-uUn1Uvlkd-YGybVA1ta4witUc4B5XPYi_qMA3NxC
dAUwkuPeZk1Fre0OMfzW9xwFNKn7_oVRLXS3CFR6CS7mAV_YVr5n3cBP7RtK-1cI_VxjWttVqgXSxrtQ7MP7RWvXEVDl-mTbYRpj6KAOIyk3X4z8B-ML_uEj
f6KUOdWnZ4ioweV_ZXLTN-fSZFuseRbYpWTzUQWlYZJ2-ExVRozWGPg1a3fzVWIv0KovWp-1t8ImFZvz4RaF3EdHvy-eyJTlmcr_KfwtaJ2LM_w48DRV3eov
sRyeI2yWhYqBs0OGa8x0cBRQGmTY_Cz1nxNiFcLMvE_4MKEPWfaSzWT0uxIa_2inb9BNEG8WWlo_-0i
}

