@startuml

!include ../a1s-lib.puml

skinparam RectangleFontColor automatic

rectangle "GRD_CLR_RED" as r1 $GRD_CLR_RED
rectangle "GRD_CLR_BLUE" as r2 $GRD_CLR_BLUE
rectangle "GRD_CLR_GREEN" as r3 $GRD_CLR_GREEN
rectangle "GRD_CLR_ORANGE" as r4 $GRD_CLR_ORANGE
rectangle "GRD_CLR_YELLOW" as r5 $GRD_CLR_YELLOW
rectangle "GRD_CLR_PURPLE" as r6 $GRD_CLR_PURPLE
rectangle "GRD_CLR_BROWN" as r7 $GRD_CLR_BROWN
rectangle "GRD_CLR_GRAY" as r8 $GRD_CLR_GRAY
rectangle "GRD_CLR_LIGHTBLUE" as r9 $GRD_CLR_LIGHTBLUE
rectangle "GRD_CLR_PINK" as r10 $GRD_CLR_PINK

rectangle "GRD_CLR_BG_PRIMARY" as r11 $GRD_CLR_BG_PRIMARY

rectangle "GRD_CLR_DARK_RED" as d1 $GRD_CLR_DARK_RED
rectangle "GRD_CLR_DARK_BLUE" as d2 $GRD_CLR_DARK_BLUE
rectangle "GRD_CLR_DARK_GREEN" as d3 $GRD_CLR_DARK_GREEN
rectangle "GRD_CLR_DARK_ORANGE" as d4 $GRD_CLR_DARK_ORANGE
rectangle "GRD_CLR_DARK_YELLOW" as d5 $GRD_CLR_DARK_YELLOW
rectangle "GRD_CLR_DARK_PURPLE" as d6 $GRD_CLR_DARK_PURPLE
rectangle "GRD_CLR_DARK_BROWN" as d7 $GRD_CLR_DARK_BROWN
rectangle "GRD_CLR_DARK_GRAY" as d8 $GRD_CLR_DARK_GRAY
rectangle "GRD_CLR_DARK_LIGHTBLUE" as d9 $GRD_CLR_DARK_LIGHTBLUE
rectangle "GRD_CLR_DARK_PINK" as d10 $GRD_CLR_DARK_PINK

@enduml
